suppressPackageStartupMessages(library(cacoa))
sc <- function(name, expr) { r <- tryCatch(withCallingHandlers(expr, message = function(m) invokeRestart("muffleMessage"), warning = function(w) { cat(sprintf("  [warn] %s\n", conditionMessage(w))); invokeRestart("muffleWarning") }), error = function(e) paste("ERROR:", conditionMessage(e))); cat(sprintf("## %s\n   %s\n", name, paste(capture.output(print(r)), collapse = "\n   "))) }
des <- function(m, i = 1) { d <- m$tests[[i]]$design; list(F = colnames(d$F), X = colnames(d$X), Z = colnames(d$Z), cF = round(d$contrast.F[abs(d$contrast.F) > 1e-12], 3), label = m$tests[[i]]$label, ref = m$tests[[i]]$levels, reason = m$tests[[i]]$reference.reason, base = d$baselines_used) }
set.seed(1); n <- 12
meta <- data.frame(group = rep(c("A", "B"), each = 6), batch = rep(c("b1", "b2"), 6), age = round(rnorm(n, 50, 6)), row.names = sprintf("s%02d", 1:n), stringsAsFactors = FALSE)
m3 <- data.frame(Group = rep(c("G1", "G2", "G3"), each = 4), Batch = rep(c("b1", "b2"), 6), age = round(rnorm(n, 50, 6)), row.names = sprintf("s%02d", 1:n), stringsAsFactors = FALSE)

sc("1a character 2-level, control-like name", { mm <- meta; mm$cond <- rep(c("disease", "control"), each = 6); des(buildCacoaModel(mm, test = "cond")) })
sc("1b factor with explicit order (disease first) overrides control-like", { mm <- meta; mm$cond <- factor(rep(c("disease", "control"), each = 6), levels = c("disease", "control")); des(buildCacoaModel(mm, test = "cond"))[c("label", "ref", "reason")] })
sc("1c logical test variable", { mm <- meta; mm$treated <- rep(c(FALSE, TRUE), each = 6); des(buildCacoaModel(mm, test = "treated"))[c("F", "label", "ref", "reason")] })
sc("1d unbalanced, no control-like name: most frequent is reference", { mm <- meta; mm$g <- c(rep("X", 8), rep("Y", 4)); des(buildCacoaModel(mm, test = "g"))[c("label", "reason")] })
sc("2a 3-level term test", des(buildCacoaModel(m3, ~ Group + Batch, test = "Group")))
sc("2b 3-level contrast G2 vs G1: baseline becomes the non-contrasted level", des(buildCacoaModel(m3, ~ Group + Batch, test = "Group: G2 vs G1")))
sc("2c 3-level contrast without nuisance", des(buildCacoaModel(m3, ~ Group, test = "Group: G2 vs G1")))
sc("2d two tests on one model: coefficient names differ between designs", { m <- buildCacoaModel(m3, ~ Group + Batch, test = c("Group: G2 vs G1", "Group: G3 vs G1", "Group")); lapply(m$tests, function(t) colnames(t$design$F)) })
sc("3a interaction formula, plain test variable", des(buildCacoaModel(meta, ~ group * batch, test = "group")))
sc("3b interaction formula, structured simple at batch b2", des(buildCacoaModel(meta, ~ group * batch, test = list(type = "simple", term = "group", num = "B", den = "A", at = list(batch = "b2")))))
sc("3c interaction formula, marginal over batch", des(buildCacoaModel(meta, ~ group * batch, test = list(type = "marginal", term = "group", num = "B", den = "A", over = "batch"))))
sc("3d interaction cell contrast", des(buildCacoaModel(meta, ~ group * batch, test = list(type = "simple", term = "group:batch", num = "B:b2", den = "A:b1"))))
sc("4a numeric test with covariate", des(buildCacoaModel(meta, ~ age + batch, test = "age")))
sc("4b numeric test with interaction age*group (slope at which group?)", des(buildCacoaModel(meta, ~ age * group, test = "age")))
sc("4c numeric test on log(age)", des(buildCacoaModel(meta, ~ log(age) + batch, test = "age")))
sc("4d numeric test on poly(age, 2)", des(buildCacoaModel(meta, ~ poly(age, 2) + batch, test = "age")))
sc("4e numeric step via triple", des(buildCacoaModel(meta, ~ age + batch, test = c("age", "60", "50")))[c("cF", "label", "ref")])
sc("5a factor() wrapper on a numeric batch", { mm <- meta; mm$batch <- rep(1:2, 6); des(buildCacoaModel(mm, ~ group + factor(batch), test = "group")) })
sc("5b numeric covariate with two distinct values stays numeric", { mm <- meta; mm$sex <- rep(0:1, 6); des(buildCacoaModel(mm, ~ group + sex, test = "all"))[c("F")] ; buildCacoaModel(mm, ~ group + sex, test = "all")$tests |> sapply(function(t) t$label) })
sc("6a missing covariate value drops the sample", { mm <- meta; mm$age[3] <- NA; m <- buildCacoaModel(mm, ~ group + age, test = "group"); list(used = length(m$samples$used), dropped = m$samples$dropped, issues = m$issues$message) })
sc("6b missing test-variable value", { mm <- meta; mm$group[3] <- NA; m <- buildCacoaModel(mm, ~ group + batch, test = "group"); list(used = length(m$samples$used), dropped = m$samples$dropped) })
sc("6c unused declared factor level", { mm <- meta; mm$group <- factor(mm$group, levels = c("A", "B", "C")); des(buildCacoaModel(mm, ~ group + batch, test = "group"))[c("F", "label")] })
sc("7a variable not in metadata", buildCacoaModel(meta, ~ group + sex, test = "group"))
sc("7b id-like column in formula", { mm <- meta; mm$sample_id <- rownames(mm); buildCacoaModel(mm, ~ group + sample_id, test = "group") })
sc("7c test on a constant column", { mm <- meta; mm$k <- "x"; buildCacoaModel(mm, test = "k") })
sc("7d test levels not present", buildCacoaModel(meta, test = "group: C vs A"))
sc("8a test = all", sapply(buildCacoaModel(meta, ~ group + age + batch, test = "all")$tests, function(t) t$label))
sc("8b coefficient-level contrast", des(buildCacoaModel(meta, ~ group + batch, test = c(groupB = 1)))[c("X", "Z", "cF", "label")])
sc("8c explicit no-intercept formula", des(buildCacoaModel(meta, ~ 0 + group + batch, test = "group")))
sc("8d block.vars added to the default formula", { m <- buildCacoaModel(meta, test = "group", block.vars = "batch"); list(formula = deparse(m$formula), perm = m$tests[[1]]$permutation[c("scheme", "n.strata", "n.distinct")]) })
sc("8e dispersion formula defaults", { m <- buildCacoaModel(meta, ~ group + age + batch, test = c("group", "age")); deparse(m$dispersion.formula) })
sc("9a model print, two-level", print(buildCacoaModel(meta, ~ group + batch, test = "group")))
sc("9b model print, interaction + marginal", print(buildCacoaModel(meta, ~ group * batch, test = list(type = "marginal", term = "group", num = "B", den = "A", over = "batch"))))
sc("10 term test with interaction formula: which columns are the term?", { d <- buildCacoaModel(meta, ~ group * batch, test = c("group: B vs A", "batch"))$tests[[2]]$design; d$term.cols })
sc("11 kernel B: a column whose observed rows lack one batch level", { d <- buildCacoaModel(meta, ~ group + batch, test = "group")$tests[[1]]$design; Y <- cbind(full = rnorm(n), nob2 = rnorm(n)); Y[meta$batch == "b2", "nob2"] <- NA; f <- cacoa:::performLMPermutations(d, Y, perm.method = "block", n.permutations = 49, seed = 1); list(effect = f$effect, p = f$pval) })
sc("12 buildDesignMatrices directly without formula (default ~0+)", { d <- buildDesignMatrices(meta, contrast = c("group", "B", "A")); list(F = colnames(d$F), X = colnames(d$X), Z = colnames(d$Z), cF = d$contrast.F) })
sc("13 three-level with explicit triple and age nuisance: numeric anchors", { d <- buildCacoaModel(m3, ~ Group * age, test = "Group: G2 vs G1"); list(des(d)[c("F", "cF")], anchors = d$tests[[1]]$design$numeric_ref_used) })
