// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// clusterFreeZScoreMat
List clusterFreeZScoreMat(const SEXP count_mat, IntegerVector sample_per_cell, List nn_ids, const std::vector<bool>& is_ref, int min_n_samp_per_cond, int min_n_obs_per_samp, bool robust, bool norm_both, double min_z, bool verbose, int n_cores, bool adjust_pvalues, int n_permutations, bool smooth, double wins);
RcppExport SEXP _cacoa_clusterFreeZScoreMat(SEXP count_matSEXP, SEXP sample_per_cellSEXP, SEXP nn_idsSEXP, SEXP is_refSEXP, SEXP min_n_samp_per_condSEXP, SEXP min_n_obs_per_sampSEXP, SEXP robustSEXP, SEXP norm_bothSEXP, SEXP min_zSEXP, SEXP verboseSEXP, SEXP n_coresSEXP, SEXP adjust_pvaluesSEXP, SEXP n_permutationsSEXP, SEXP smoothSEXP, SEXP winsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP >::type count_mat(count_matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sample_per_cell(sample_per_cellSEXP);
    Rcpp::traits::input_parameter< List >::type nn_ids(nn_idsSEXP);
    Rcpp::traits::input_parameter< const std::vector<bool>& >::type is_ref(is_refSEXP);
    Rcpp::traits::input_parameter< int >::type min_n_samp_per_cond(min_n_samp_per_condSEXP);
    Rcpp::traits::input_parameter< int >::type min_n_obs_per_samp(min_n_obs_per_sampSEXP);
    Rcpp::traits::input_parameter< bool >::type robust(robustSEXP);
    Rcpp::traits::input_parameter< bool >::type norm_both(norm_bothSEXP);
    Rcpp::traits::input_parameter< double >::type min_z(min_zSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< bool >::type adjust_pvalues(adjust_pvaluesSEXP);
    Rcpp::traits::input_parameter< int >::type n_permutations(n_permutationsSEXP);
    Rcpp::traits::input_parameter< bool >::type smooth(smoothSEXP);
    Rcpp::traits::input_parameter< double >::type wins(winsSEXP);
    rcpp_result_gen = Rcpp::wrap(clusterFreeZScoreMat(count_mat, sample_per_cell, nn_ids, is_ref, min_n_samp_per_cond, min_n_obs_per_samp, robust, norm_both, min_z, verbose, n_cores, adjust_pvalues, n_permutations, smooth, wins));
    return rcpp_result_gen;
END_RCPP
}
// estimateCorrelationDistance
double estimateCorrelationDistance(const Eigen::VectorXd& v1, const Eigen::VectorXd& v2, bool centered);
RcppExport SEXP _cacoa_estimateCorrelationDistance(SEXP v1SEXP, SEXP v2SEXP, SEXP centeredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type v2(v2SEXP);
    Rcpp::traits::input_parameter< bool >::type centered(centeredSEXP);
    rcpp_result_gen = Rcpp::wrap(estimateCorrelationDistance(v1, v2, centered));
    return rcpp_result_gen;
END_RCPP
}
// estimateClusterFreeExpressionShiftsInfo
List estimateClusterFreeExpressionShiftsInfo(const Eigen::SparseMatrix<double>& cm, IntegerVector sample_per_cell, List nn_ids, int min_n_obs_per_samp, bool verbose, int n_cores, const std::string& dist, bool log_vecs);
RcppExport SEXP _cacoa_estimateClusterFreeExpressionShiftsInfo(SEXP cmSEXP, SEXP sample_per_cellSEXP, SEXP nn_idsSEXP, SEXP min_n_obs_per_sampSEXP, SEXP verboseSEXP, SEXP n_coresSEXP, SEXP distSEXP, SEXP log_vecsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type cm(cmSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sample_per_cell(sample_per_cellSEXP);
    Rcpp::traits::input_parameter< List >::type nn_ids(nn_idsSEXP);
    Rcpp::traits::input_parameter< int >::type min_n_obs_per_samp(min_n_obs_per_sampSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dist(distSEXP);
    Rcpp::traits::input_parameter< bool >::type log_vecs(log_vecsSEXP);
    rcpp_result_gen = Rcpp::wrap(estimateClusterFreeExpressionShiftsInfo(cm, sample_per_cell, nn_ids, min_n_obs_per_samp, verbose, n_cores, dist, log_vecs));
    return rcpp_result_gen;
END_RCPP
}
// estimateClusterFreeExpressionShiftsC
List estimateClusterFreeExpressionShiftsC(const Eigen::SparseMatrix<double>& cm, IntegerVector sample_per_cell, List nn_ids, const std::vector<bool>& is_ref, const int min_n_between, const int min_n_within, const int min_n_obs_per_samp, bool norm_all, bool verbose, int n_cores, const std::string& dist, bool log_vecs, int n_permutations, bool smooth, double wins, int seed);
RcppExport SEXP _cacoa_estimateClusterFreeExpressionShiftsC(SEXP cmSEXP, SEXP sample_per_cellSEXP, SEXP nn_idsSEXP, SEXP is_refSEXP, SEXP min_n_betweenSEXP, SEXP min_n_withinSEXP, SEXP min_n_obs_per_sampSEXP, SEXP norm_allSEXP, SEXP verboseSEXP, SEXP n_coresSEXP, SEXP distSEXP, SEXP log_vecsSEXP, SEXP n_permutationsSEXP, SEXP smoothSEXP, SEXP winsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type cm(cmSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sample_per_cell(sample_per_cellSEXP);
    Rcpp::traits::input_parameter< List >::type nn_ids(nn_idsSEXP);
    Rcpp::traits::input_parameter< const std::vector<bool>& >::type is_ref(is_refSEXP);
    Rcpp::traits::input_parameter< const int >::type min_n_between(min_n_betweenSEXP);
    Rcpp::traits::input_parameter< const int >::type min_n_within(min_n_withinSEXP);
    Rcpp::traits::input_parameter< const int >::type min_n_obs_per_samp(min_n_obs_per_sampSEXP);
    Rcpp::traits::input_parameter< bool >::type norm_all(norm_allSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dist(distSEXP);
    Rcpp::traits::input_parameter< bool >::type log_vecs(log_vecsSEXP);
    Rcpp::traits::input_parameter< int >::type n_permutations(n_permutationsSEXP);
    Rcpp::traits::input_parameter< bool >::type smooth(smoothSEXP);
    Rcpp::traits::input_parameter< double >::type wins(winsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(estimateClusterFreeExpressionShiftsC(cm, sample_per_cell, nn_ids, is_ref, min_n_between, min_n_within, min_n_obs_per_samp, norm_all, verbose, n_cores, dist, log_vecs, n_permutations, smooth, wins, seed));
    return rcpp_result_gen;
END_RCPP
}
// mapIds
std::vector<std::vector<int>> mapIds(std::vector<std::vector<int>> ids_vec, std::vector<int> id_map);
RcppExport SEXP _cacoa_mapIds(SEXP ids_vecSEXP, SEXP id_mapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::vector<int>> >::type ids_vec(ids_vecSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type id_map(id_mapSEXP);
    rcpp_result_gen = Rcpp::wrap(mapIds(ids_vec, id_map));
    return rcpp_result_gen;
END_RCPP
}
// clusterFreeGeneMat
Rcpp::NumericMatrix clusterFreeGeneMat(const SEXP count_mat, Rcpp::IntegerVector sample_per_cell, Rcpp::List nn_ids, int min_n_obs_per_samp, int gi);
RcppExport SEXP _cacoa_clusterFreeGeneMat(SEXP count_matSEXP, SEXP sample_per_cellSEXP, SEXP nn_idsSEXP, SEXP min_n_obs_per_sampSEXP, SEXP giSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP >::type count_mat(count_matSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type sample_per_cell(sample_per_cellSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type nn_ids(nn_idsSEXP);
    Rcpp::traits::input_parameter< int >::type min_n_obs_per_samp(min_n_obs_per_sampSEXP);
    Rcpp::traits::input_parameter< int >::type gi(giSEXP);
    rcpp_result_gen = Rcpp::wrap(clusterFreeGeneMat(count_mat, sample_per_cell, nn_ids, min_n_obs_per_samp, gi));
    return rcpp_result_gen;
END_RCPP
}
// estimateExpressionShiftsPairsLM
arma::mat estimateExpressionShiftsPairsLM(const Eigen::SparseMatrix<double>& cm, Rcpp::IntegerVector sample_per_cell, Rcpp::List nn_ids, const arma::imat& pairs_mat, int min_n_obs_per_samp, std::string dist, bool log_vecs);
RcppExport SEXP _cacoa_estimateExpressionShiftsPairsLM(SEXP cmSEXP, SEXP sample_per_cellSEXP, SEXP nn_idsSEXP, SEXP pairs_matSEXP, SEXP min_n_obs_per_sampSEXP, SEXP distSEXP, SEXP log_vecsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type cm(cmSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type sample_per_cell(sample_per_cellSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type nn_ids(nn_idsSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type pairs_mat(pairs_matSEXP);
    Rcpp::traits::input_parameter< int >::type min_n_obs_per_samp(min_n_obs_per_sampSEXP);
    Rcpp::traits::input_parameter< std::string >::type dist(distSEXP);
    Rcpp::traits::input_parameter< bool >::type log_vecs(log_vecsSEXP);
    rcpp_result_gen = Rcpp::wrap(estimateExpressionShiftsPairsLM(cm, sample_per_cell, nn_ids, pairs_mat, min_n_obs_per_samp, dist, log_vecs));
    return rcpp_result_gen;
END_RCPP
}
// applyMedianFilterES
std::vector<double> applyMedianFilterES(const std::vector<double>& x, Rcpp::List nn_ids, Rcpp::Nullable<Rcpp::IntegerVector> non_zero_ids, bool one_based);
RcppExport SEXP _cacoa_applyMedianFilterES(SEXP xSEXP, SEXP nn_idsSEXP, SEXP non_zero_idsSEXP, SEXP one_basedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double>& >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type nn_ids(nn_idsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type non_zero_ids(non_zero_idsSEXP);
    Rcpp::traits::input_parameter< bool >::type one_based(one_basedSEXP);
    rcpp_result_gen = Rcpp::wrap(applyMedianFilterES(x, nn_ids, non_zero_ids, one_based));
    return rcpp_result_gen;
END_RCPP
}
// adjustedZScoresMaxStat
std::vector<double> adjustedZScoresMaxStat(const std::vector<double>& z_obs, int alt, const Rcpp::NumericVector& max_vals_in, const Rcpp::NumericVector& min_vals_in, double wins, bool smooth, Rcpp::Nullable<Rcpp::List> nn_ids, Rcpp::Nullable<Rcpp::IntegerVector> non_zero_ids);
RcppExport SEXP _cacoa_adjustedZScoresMaxStat(SEXP z_obsSEXP, SEXP altSEXP, SEXP max_vals_inSEXP, SEXP min_vals_inSEXP, SEXP winsSEXP, SEXP smoothSEXP, SEXP nn_idsSEXP, SEXP non_zero_idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double>& >::type z_obs(z_obsSEXP);
    Rcpp::traits::input_parameter< int >::type alt(altSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type max_vals_in(max_vals_inSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type min_vals_in(min_vals_inSEXP);
    Rcpp::traits::input_parameter< double >::type wins(winsSEXP);
    Rcpp::traits::input_parameter< bool >::type smooth(smoothSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type nn_ids(nn_idsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type non_zero_ids(non_zero_idsSEXP);
    rcpp_result_gen = Rcpp::wrap(adjustedZScoresMaxStat(z_obs, alt, max_vals_in, min_vals_in, wins, smooth, nn_ids, non_zero_ids));
    return rcpp_result_gen;
END_RCPP
}
// fit_and_randomize
Rcpp::List fit_and_randomize(const arma::mat& X, const arma::mat& Y, const arma::vec& contrast, Rcpp::Nullable<Rcpp::List> perm_groups, Rcpp::Nullable<arma::umat> pair_indices, int n_randomizations, std::string alternative, bool return_residuals, bool return_sampled_fits, bool return_sampled_stats, std::string robust, double huber_k, int huber_maxit, double huber_tol, std::string na_mode, double na_weight, std::string na_center, double illcond_rcond, double pinv_tol, int n_cores, int seed);
RcppExport SEXP _cacoa_fit_and_randomize(SEXP XSEXP, SEXP YSEXP, SEXP contrastSEXP, SEXP perm_groupsSEXP, SEXP pair_indicesSEXP, SEXP n_randomizationsSEXP, SEXP alternativeSEXP, SEXP return_residualsSEXP, SEXP return_sampled_fitsSEXP, SEXP return_sampled_statsSEXP, SEXP robustSEXP, SEXP huber_kSEXP, SEXP huber_maxitSEXP, SEXP huber_tolSEXP, SEXP na_modeSEXP, SEXP na_weightSEXP, SEXP na_centerSEXP, SEXP illcond_rcondSEXP, SEXP pinv_tolSEXP, SEXP n_coresSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type contrast(contrastSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type perm_groups(perm_groupsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::umat> >::type pair_indices(pair_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type n_randomizations(n_randomizationsSEXP);
    Rcpp::traits::input_parameter< std::string >::type alternative(alternativeSEXP);
    Rcpp::traits::input_parameter< bool >::type return_residuals(return_residualsSEXP);
    Rcpp::traits::input_parameter< bool >::type return_sampled_fits(return_sampled_fitsSEXP);
    Rcpp::traits::input_parameter< bool >::type return_sampled_stats(return_sampled_statsSEXP);
    Rcpp::traits::input_parameter< std::string >::type robust(robustSEXP);
    Rcpp::traits::input_parameter< double >::type huber_k(huber_kSEXP);
    Rcpp::traits::input_parameter< int >::type huber_maxit(huber_maxitSEXP);
    Rcpp::traits::input_parameter< double >::type huber_tol(huber_tolSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_mode(na_modeSEXP);
    Rcpp::traits::input_parameter< double >::type na_weight(na_weightSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_center(na_centerSEXP);
    Rcpp::traits::input_parameter< double >::type illcond_rcond(illcond_rcondSEXP);
    Rcpp::traits::input_parameter< double >::type pinv_tol(pinv_tolSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_and_randomize(X, Y, contrast, perm_groups, pair_indices, n_randomizations, alternative, return_residuals, return_sampled_fits, return_sampled_stats, robust, huber_k, huber_maxit, huber_tol, na_mode, na_weight, na_center, illcond_rcond, pinv_tol, n_cores, seed));
    return rcpp_result_gen;
END_RCPP
}
// fl_fwl_cpp
Rcpp::List fl_fwl_cpp(const arma::mat& X, const arma::mat& Z, const arma::mat& Y, const arma::vec& contrast, SEXP core_rows, Rcpp::Nullable<Rcpp::List> core_perm_groups, Rcpp::Nullable<arma::umat> core_pair_indices, int n_randomizations, std::string alternative, std::string robust, double huber_k, int huber_maxit, double huber_tol, std::string na_mode, double na_weight, std::string na_center, double illcond_rcond, double pinv_tol, int n_cores, bool return_residuals, bool return_sampled_fits, bool return_sampled_stats, int seed);
RcppExport SEXP _cacoa_fl_fwl_cpp(SEXP XSEXP, SEXP ZSEXP, SEXP YSEXP, SEXP contrastSEXP, SEXP core_rowsSEXP, SEXP core_perm_groupsSEXP, SEXP core_pair_indicesSEXP, SEXP n_randomizationsSEXP, SEXP alternativeSEXP, SEXP robustSEXP, SEXP huber_kSEXP, SEXP huber_maxitSEXP, SEXP huber_tolSEXP, SEXP na_modeSEXP, SEXP na_weightSEXP, SEXP na_centerSEXP, SEXP illcond_rcondSEXP, SEXP pinv_tolSEXP, SEXP n_coresSEXP, SEXP return_residualsSEXP, SEXP return_sampled_fitsSEXP, SEXP return_sampled_statsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type contrast(contrastSEXP);
    Rcpp::traits::input_parameter< SEXP >::type core_rows(core_rowsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type core_perm_groups(core_perm_groupsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::umat> >::type core_pair_indices(core_pair_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type n_randomizations(n_randomizationsSEXP);
    Rcpp::traits::input_parameter< std::string >::type alternative(alternativeSEXP);
    Rcpp::traits::input_parameter< std::string >::type robust(robustSEXP);
    Rcpp::traits::input_parameter< double >::type huber_k(huber_kSEXP);
    Rcpp::traits::input_parameter< int >::type huber_maxit(huber_maxitSEXP);
    Rcpp::traits::input_parameter< double >::type huber_tol(huber_tolSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_mode(na_modeSEXP);
    Rcpp::traits::input_parameter< double >::type na_weight(na_weightSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_center(na_centerSEXP);
    Rcpp::traits::input_parameter< double >::type illcond_rcond(illcond_rcondSEXP);
    Rcpp::traits::input_parameter< double >::type pinv_tol(pinv_tolSEXP);
    Rcpp::traits::input_parameter< int >::type n_cores(n_coresSEXP);
    Rcpp::traits::input_parameter< bool >::type return_residuals(return_residualsSEXP);
    Rcpp::traits::input_parameter< bool >::type return_sampled_fits(return_sampled_fitsSEXP);
    Rcpp::traits::input_parameter< bool >::type return_sampled_stats(return_sampled_statsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(fl_fwl_cpp(X, Z, Y, contrast, core_rows, core_perm_groups, core_pair_indices, n_randomizations, alternative, robust, huber_k, huber_maxit, huber_tol, na_mode, na_weight, na_center, illcond_rcond, pinv_tol, n_cores, return_residuals, return_sampled_fits, return_sampled_stats, seed));
    return rcpp_result_gen;
END_RCPP
}
// permuted_contrast_F
arma::vec permuted_contrast_F(const arma::mat& G, const arma::vec& a, const arma::mat& H, double cXc, int q, const arma::imat& P);
RcppExport SEXP _cacoa_permuted_contrast_F(SEXP GSEXP, SEXP aSEXP, SEXP HSEXP, SEXP cXcSEXP, SEXP qSEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type H(HSEXP);
    Rcpp::traits::input_parameter< double >::type cXc(cXcSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(permuted_contrast_F(G, a, H, cXc, q, P));
    return rcpp_result_gen;
END_RCPP
}
// permuted_contrast_F_fl
arma::vec permuted_contrast_F_fl(const arma::mat& K1, const arma::mat& K2, const arma::mat& K3, const arma::mat& K4, const arma::vec& a, const arma::mat& H, double cXc, int q, const arma::imat& P);
RcppExport SEXP _cacoa_permuted_contrast_F_fl(SEXP K1SEXP, SEXP K2SEXP, SEXP K3SEXP, SEXP K4SEXP, SEXP aSEXP, SEXP HSEXP, SEXP cXcSEXP, SEXP qSEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type K1(K1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type K2(K2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type K3(K3SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type K4(K4SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type H(HSEXP);
    Rcpp::traits::input_parameter< double >::type cXc(cXcSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type P(PSEXP);
    rcpp_result_gen = Rcpp::wrap(permuted_contrast_F_fl(K1, K2, K3, K4, a, H, cXc, q, P));
    return rcpp_result_gen;
END_RCPP
}
// projdiff
arma::rowvec projdiff(const arma::mat& mat, const arma::ivec& g1, const arma::ivec& g2);
RcppExport SEXP _cacoa_projdiff(SEXP matSEXP, SEXP g1SEXP, SEXP g2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type g1(g1SEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type g2(g2SEXP);
    rcpp_result_gen = Rcpp::wrap(projdiff(mat, g1, g2));
    return rcpp_result_gen;
END_RCPP
}
// fit_density_lm
Rcpp::List fit_density_lm(const arma::mat& M, const arma::mat& P, int n_randomizations);
RcppExport SEXP _cacoa_fit_density_lm(SEXP MSEXP, SEXP PSEXP, SEXP n_randomizationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type P(PSEXP);
    Rcpp::traits::input_parameter< int >::type n_randomizations(n_randomizationsSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_density_lm(M, P, n_randomizations));
    return rcpp_result_gen;
END_RCPP
}
// perm_full_contrast_mat
List perm_full_contrast_mat(const arma::mat& F, const arma::mat& Y, const arma::vec& contrastF, const arma::uvec& blocks, const int B);
RcppExport SEXP _cacoa_perm_full_contrast_mat(SEXP FSEXP, SEXP YSEXP, SEXP contrastFSEXP, SEXP blocksSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type F(FSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type contrastF(contrastFSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type blocks(blocksSEXP);
    Rcpp::traits::input_parameter< const int >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(perm_full_contrast_mat(F, Y, contrastF, blocks, B));
    return rcpp_result_gen;
END_RCPP
}
// perm_FL_contrast_mat
List perm_FL_contrast_mat(const arma::mat& Xr, const arma::mat& Yr, const arma::vec& contrastX, const arma::uvec& blocks, const int B);
RcppExport SEXP _cacoa_perm_FL_contrast_mat(SEXP XrSEXP, SEXP YrSEXP, SEXP contrastXSEXP, SEXP blocksSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xr(XrSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Yr(YrSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type contrastX(contrastXSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type blocks(blocksSEXP);
    Rcpp::traits::input_parameter< const int >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(perm_FL_contrast_mat(Xr, Yr, contrastX, blocks, B));
    return rcpp_result_gen;
END_RCPP
}
// colwiseBinaryDistance
NumericMatrix colwiseBinaryDistance(IntegerMatrix mat);
RcppExport SEXP _cacoa_colwiseBinaryDistance(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(colwiseBinaryDistance(mat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cacoa_clusterFreeZScoreMat", (DL_FUNC) &_cacoa_clusterFreeZScoreMat, 15},
    {"_cacoa_estimateCorrelationDistance", (DL_FUNC) &_cacoa_estimateCorrelationDistance, 3},
    {"_cacoa_estimateClusterFreeExpressionShiftsInfo", (DL_FUNC) &_cacoa_estimateClusterFreeExpressionShiftsInfo, 8},
    {"_cacoa_estimateClusterFreeExpressionShiftsC", (DL_FUNC) &_cacoa_estimateClusterFreeExpressionShiftsC, 16},
    {"_cacoa_mapIds", (DL_FUNC) &_cacoa_mapIds, 2},
    {"_cacoa_clusterFreeGeneMat", (DL_FUNC) &_cacoa_clusterFreeGeneMat, 5},
    {"_cacoa_estimateExpressionShiftsPairsLM", (DL_FUNC) &_cacoa_estimateExpressionShiftsPairsLM, 7},
    {"_cacoa_applyMedianFilterES", (DL_FUNC) &_cacoa_applyMedianFilterES, 4},
    {"_cacoa_adjustedZScoresMaxStat", (DL_FUNC) &_cacoa_adjustedZScoresMaxStat, 8},
    {"_cacoa_fit_and_randomize", (DL_FUNC) &_cacoa_fit_and_randomize, 21},
    {"_cacoa_fl_fwl_cpp", (DL_FUNC) &_cacoa_fl_fwl_cpp, 23},
    {"_cacoa_permuted_contrast_F", (DL_FUNC) &_cacoa_permuted_contrast_F, 6},
    {"_cacoa_permuted_contrast_F_fl", (DL_FUNC) &_cacoa_permuted_contrast_F_fl, 9},
    {"_cacoa_projdiff", (DL_FUNC) &_cacoa_projdiff, 3},
    {"_cacoa_fit_density_lm", (DL_FUNC) &_cacoa_fit_density_lm, 3},
    {"_cacoa_perm_full_contrast_mat", (DL_FUNC) &_cacoa_perm_full_contrast_mat, 5},
    {"_cacoa_perm_FL_contrast_mat", (DL_FUNC) &_cacoa_perm_FL_contrast_mat, 5},
    {"_cacoa_colwiseBinaryDistance", (DL_FUNC) &_cacoa_colwiseBinaryDistance, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_cacoa(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
