#' @importFrom sccore checkPackageInstalled
NULL

#' Estimate expression shift magnitudes per cell type between conditions
#'
#' This function estimates the magnitude of expression changes (shifts) between
#' conditions using a pairwise distance approach. It supports two modes of analysis:
#'
#' \strong{1. Standard Mode (Static):}
#' Uses the full set of genes provided in \code{cm.per.type} to calculate a single,
#' static pairwise distance matrix \code{Y}. Permutation testing is performed by
#' shuffling residuals (Freedman-Lane) or blocks within the linear model \code{Y ~ Model}.
#'
#' \strong{2. Gene Focusing Mode (Dynamic):}
#' Triggered when \code{top.n.genes} is specified. In this mode, genes are
#' dynamically selected in every permutation step.
#' \itemize{
#'   \item For the observed data (and each randomization), the function ranks genes
#'         by their association with the sample-level contrast (using a t-test or Wilcoxon equivalent).
#'   \item Pairwise distances are computed using only the top \eqn{N} selected genes.
#'   \item The test statistic is the correlation of these focused distances with the pair-level design.
#' }
#' This mode tests whether the \emph{most differentially expressed} genes drive a
#' significant global shift, accounting for the selection bias via permutation.
#'
#' @param cm.per.type List of normalized count matrices per cell type (samples x genes).
#' @param cell.groups Named factor defining cell types/clusters for summary tables.
#' @param pair.model A paired design object (list) generated by \code{buildPairDesignMatrices}.
#'        Must contain the pair-level design matrices \code{$X} (core) and \code{$Z} (nuisance),
#'        and the contrast \code{$contrast.X}.
#' @param sample.per.cell Named vector indicating the sample ID for each cell.
#' @param sample.ids Character vector of sample IDs aligning with the rows of the
#'        design matrices. \strong{Required} for the Gene Focusing path to align
#'        expression matrices with \code{sample.model}.
#' @param dist Distance metric to use:
#'        \itemize{
#'          \item \code{"cor"} (default): Pearson correlation distance (1 - r).
#'                In focusing mode, this centers the data before computing cosine similarity.
#'          \item \code{"l2"}: Euclidean distance.
#'          \item \code{"l1"}: Manhattan distance.
#'        }
#' @param dist.type Type of shift to estimate (mostly for visualization/compatibility):
#'        \code{"shift"} (default), \code{"total"}, or \code{"var"}.
#' @param perm.method Permutation method for the Standard Path:
#'        \code{"freedman-lane"} (default) or \code{"block"}.
#'        (Note: The Focusing path uses a specialized randomization of the sample-level
#'        contrast and ignores this argument).
#' @param robust.method Robust regression method for the linear model:
#'        \code{"none"} (default), \code{"huber"}, or \code{"winsor"}.
#' @param na.mode How to handle \code{NA} values in distance matrices:
#'        \code{"drop"} (default) or \code{"impute_weak"}.
#' @param alternative Alternative hypothesis: \code{"two-sided"} (default),
#'        \code{"greater"}, or \code{"less"}.
#' @param n.permutations Number of permutations to perform (default=1000).
#' @param p.adjust.method Method for p-value adjustment (default="BH").
#' @param top.n.genes Integer. If provided, triggers the **Gene Focusing** path.
#'        The function will select this many top ranking genes (based on \code{gene.selection})
#'        to compute distances in every permutation.
#' @param gene.selection Method to rank genes for focusing:
#'        \code{"t-test"} (default) or \code{"wilcox"}.
#'        Requires \code{sample.model} to be provided.
#' @param sample.model The sample-level design object (from \code{buildDesignMatrices}).
#'        \strong{Required} if \code{top.n.genes} is used. This provides the
#'        sample-level design matrix and contrast used to rank genes.
#' @param n.cores Number of cores for parallel processing (default=1).
#' @param verbose Logical; print progress messages (default=TRUE).
#' @param ... Additional arguments passed to internal functions.
#'
#' @return A list containing:
#' \describe{
#'   \item{results}{Data frame of summary statistics per cell type (stat, p-value, z-score, adj.p).}
#'   \item{res}{Detailed results from the permutation test (pairwise distance matrix, observed stats, permuted stats, residuals, etc.).}
#'   \item{r2}{R-squared estimates for the model terms.}
#'   \item{dist.type, perm.method, ...}{Input parameters returned for reference.}
#' }
#'
#' @export
estimateExpressionChange <- function(cm.per.type, cell.groups, pair.model, sample.per.cell,
                                     sample.model = NULL, sample.ids = NULL, dist = "cor", dist.type = c("shift", "total", "var"), 
                                     perm.method = c("freedman-lane", "block"), robust.method = c("none", "huber", "winsor"),
                                     na.mode = c("drop", "impute_weak"), alternative = c("two-sided", "greater", "less"),
                                     n.permutations = 1000, p.adjust.method = "BH", trim = 0.2, return.residuals = FALSE, 
                                     return.sampled.stats = TRUE, return.sampled.fits = FALSE, 
                                     top.n.genes = NULL, gene.selection = c("t-test", "wilcox"), 
                                     n.cores = 1, verbose = TRUE, ...) {
  
  dist.type <- match.arg(dist.type)
  perm.method <- match.arg(perm.method)
  robust.method <- match.arg(robust.method)
  na.mode <- match.arg(na.mode)
  gene.selection <- match.arg(gene.selection)
  
  cell.groups <- droplevels(factor(cell.groups))
  sample.type.table <- table(cell.groups, sample.per.cell[names(cell.groups)])
  
  # --- FOCUSING PATH CHECK ---
  # Trigger if top.n.genes is set and meaningful (less than total genes available)
  n_total_genes <- if(length(cm.per.type) > 0) ncol(cm.per.type[[1]]) else 0
  use.focusing <- !is.null(top.n.genes) && (n_total_genes > top.n.genes)
  
  if (use.focusing) { # focused path
    if (verbose) message(sprintf("Using gene focusing path (top %d genes via %s)...", top.n.genes, gene.selection))
    
    if(is.null(sample.model)) stop("Gene focusing path requires 'sample.model' to perform gene selection.")
    if(is.null(sample.ids)) stop("Gene focusing path requires 'sample.ids' to align matrices.")
    
    # 1. Run Focusing Engine (get valid P-values, Z-scores, and Observed Y)
    focus.res <- fitWithFocusingWrapper(
      cm.per.type = cm.per.type, 
      pair.model = pair.model, 
      sample.model = sample.model,
      sample.ids = sample.ids,
      top.n.genes = top.n.genes, 
      gene.selection = gene.selection,
      dist = dist,
      n.permutations = n.permutations, 
      alternative = alternative,
      n.cores = n.cores,
      na.mode = na.mode,
      robust.method = robust.method
    )
    
    # 2. Refit using Standard Engine on Observed Y (n.permutations = 0)
    # This generates coefficients and residuals matching the standard output structure.
    # We pass the same robust/na settings to match the focusing logic.
    res <- performLMPermutations(
      y = focus.res$sample.distances, 
      x = pair.model, 
      n.permutations = 0, # No perms, just fit
      perm.method = perm.method, 
      robust.method = robust.method, 
      na.mode = na.mode, 
      alternative = alternative,
      return.residuals = return.residuals, 
      n.cores = n.cores, 
      ...
    )
    
    # 3. Inject Focusing Statistics
    # We overwrite the parametric/dummy stats from the 0-perm fit with the 
    # correct permutation-based stats from the focusing engine.
    res$stat.obs   <- focus.res$stat.obs
    res$pval       <- focus.res$pval
    res$z.score    <- focus.res$z.score
    res$stats.perm <- focus.res$stats.perm
    res$sample.distances <- focus.res$sample.distances
    
  } else { # non-focused path
 
    # Pairwise Distances (Static, All genes)
    p.dist <- estimateExpressionShiftsForCellType(cm.per.type, dist = dist, pair.model = pair.model, sample.ids = sample.ids)
    
    # Fitting and randomization
    res <- performLMPermutations(y = p.dist$Y, x = pair.model, n.permutations = n.permutations, perm.method = perm.method, 
                                 robust.method = robust.method, na.mode = na.mode, alternative = alternative,
                                 return.residuals = return.residuals, return.sampled.stats = return.sampled.stats,
                                 return.sampled.fits = return.sampled.fits, n.cores = n.cores, ...)
    
    res$sample.distances <- p.dist$Y
  }
  
  # --- COMMON POST-PROCESSING ---
  
  # R2 estimation (standard for both, using the Y matrix from either path)
  r2 <- estimateR2PerTerm(pair.model$F, res$sample.distances, groups = makeGroupsPair(pair.model$F))
  
  if (verbose) message("Done!\n")
  ct <- levels(cell.groups)
  
  # Ensure result names match cell types (Handling cases where some types might be dropped)
  names(res$stat.obs) <- names(res$pval) <- names(res$z.score) <- ct
  summary  <- data.frame(celltype=ct, obs.stat=res$stat.obs, pvalue=res$pval, zscore=res$z.score, stringsAsFactors=FALSE)
  summary$padjust <- p.adjust(summary$pvalue, method=p.adjust.method)
  summary <- summary[order(summary$obs.stat, decreasing=TRUE), ]
  
  out <- list(results= summary, res = res, perm.method = perm.method, robust.method= robust.method,
              dist.type = dist.type, r2 = r2, sample.table = sample.type.table, design.mat = pair.model
  )
  out
}

#' Wrapper for C++ gene focusing engine
#' @keywords internal
#' Wrapper for C++ gene focusing engine
#' @keywords internal
#' Wrapper for C++ gene focusing engine
#' @keywords internal
fitWithFocusingWrapper <- function(cm.per.type, pair.model, sample.model, sample.ids,
                                   top.n.genes, gene.selection, dist, 
                                   n.permutations, alternative, n.cores, 
                                   na.mode = "drop", robust.method = "none", ...) {
  
  # --- 1. Dist Type Mapping & Pre-processing ---
  # Center samples in R to match Pearson in C++
  cpp_dist_type <- dist
  
  cm_input <- lapply(cm.per.type, function(M) {
    if (is.null(M)) return(NULL)
    
    # If M is already perfectly aligned, return as is
    if (nrow(M) == length(sample.ids) && all(rownames(M) == sample.ids)) {
      M_aligned <- M
    } else {
      # Otherwise expand/reorder
      M_aligned <- matrix(NA_real_, nrow = length(sample.ids), ncol = ncol(M), 
                          dimnames = list(sample.ids, colnames(M)))
      common <- intersect(sample.ids, rownames(M))
      if (length(common) > 0) {
        M_aligned[common, ] <- M[common, ]
      }
    }
    
    # R-side Centering logic (Column centering) for Correlation
    if (dist == "cor") {
      gene_means <- colMeans(M_aligned, na.rm = TRUE)
      M_aligned <- sweep(M_aligned, 2, gene_means, "-")
    }
    return(M_aligned)
  })
  
  # Handle dist code for C++
  if (dist == "cor") {
    cpp_dist_type <- "cosine" 
  }
  
  # --- 2. Prepare C++ Inputs ---
  pair_Z <- if (!is.null(pair.model$Z)) as.matrix(pair.model$Z) else matrix(0, 0, 0)
  
  # Pass explicit pairs (converted to 0-based) to ensure C++ loop order 
  # matches the R design matrix order.
  pairs_0 <- as.matrix(pair.model$pairs) - 1
  
  # --- 3. Call C++ Engine ---
  res_cpp <- fit_with_focusing(
    M_list = cm_input,                   
    sample_X = as.matrix(sample.model$X),           
    sample_contrast = sample.model$contrast.X, 
    pair_X = as.matrix(pair.model$X),
    pairs = pairs_0,                     
    pair_Z = pair_Z,                     
    pair_contrast = pair.model$contrast.X, 
    sample_perm_groups = sample.model$perm.groups$full,
    n_randomizations = n.permutations,
    n_top_features = top.n.genes,
    test_type = gene.selection,
    dist_type = cpp_dist_type,
    robust = robust.method,
    na_mode = na.mode,
    n_cores = n.cores
  )
  
  # --- 4. Format Outputs ---
  stat.obs   <- as.vector(res_cpp$stat)
  pvals      <- as.vector(res_cpp$p_value)
  perm.stats <- res_cpp$perm_stats
  obs_Y      <- res_cpp$Y
  
  # Handle NAs
  stat.obs[is.na(stat.obs)] <- 0
  pvals[is.na(pvals)] <- 1
  
  # Z-scores
  p_clamped <- pmin(pmax(pvals, 1e-16), 1 - 1e-16)
  z.scores <- if (alternative == "two-sided") {
    qnorm(1 - p_clamped / 2) * sign(stat.obs)
  } else if (alternative == "greater") {
    qnorm(1 - p_clamped)
  } else { 
    qnorm(p_clamped)
  }
  
  ct_names <- names(cm.per.type)
  names(stat.obs) <- names(pvals) <- names(z.scores) <- ct_names
  if(!is.null(perm.stats)) colnames(perm.stats) <- ct_names
  
  # Format Y matrix
  if (!is.null(obs_Y)) {
    colnames(obs_Y) <- ct_names
    # Reconstruct pair names
    idx <- pair.model$pairs
    pair.names <- paste(sample.ids[idx[, 1]], sample.ids[idx[, 2]], sep = "__")
    rownames(obs_Y) <- pair.names
  }
  
  list(
    stat.obs = stat.obs,
    stats.perm = perm.stats,
    pval = pvals,
    z.score = z.scores,
    sample.distances = obs_Y
  )
}


#' Estimate pairwise expression distances for all cell types in a paired design
#'
#' This function computes **sample–sample distance matrices** within each cell type
#' and then vectorizes them into a common pairwise layout defined by
#' `buildPairDesignMatrices()`. For every cell type, it:
#' \enumerate{
#'   \item Takes its normalized count matrix (`samples × genes`);
#'   \item Computes a square distance matrix over samples using the chosen metric
#'         (`"cor"`, `"l2"`, or `"l1"`);
#'   \item Extracts the distances for the global pairs in \code{pair.model$pairs},
#'         mapping via \code{sample.ids}.
#' }
#' Steps performed internally:
#'
#'   1. Validate inputs:
#'        - `cm.norm` must be a list of sample × gene matrices (one per cell type).
#'        - `pair.model$pairs` must be an N×2 matrix of global sample indices.
#'        - `sample.ids` must be long enough to index all pairs.
#'   2. Construct human-readable pair names of the form
#'        `"SampleA__SampleB"` for every `(i, j)` in `pair.model$pairs`.
#'   3. Allocate the output matrix `Y` with:
#'        - one row per global sample pair,
#'        - one column per cell type.
#'   4. For each cell type:
#'        - Extract its normalized expression matrix (samples × genes).
#'        - Compute a full sample–sample distance matrix using the selected
#'          measure (`"cor"`, `"l2"`, or `"l1"`).
#'        - Ensure row names of the distance matrix correspond to sample IDs.
#'   5. Map global pairs to local distances:
#'        - Convert global sample indices to sample IDs using `sample.ids`.
#'        - Match these IDs to the distance-matrix row names.
#'        - For each pair `(i, j)`:
#'             • If **both samples are present** in this cell type, extract `D[i, j]`.  
#'             • If **either sample is missing** (the type does not occur in that sample),
#'               store `NA`.  
#'             • If the distance measure cannot be computed due to missing genes or
#'               incomplete rows, the resulting distance is also `NA`.
#'   6. Fill the appropriate column of `Y` with these mapped distances for
#'      the current cell type.
#' 
#'  NOTE: Any gene filtering or PCA steps have been removed from this function; 
#
# The result is a matrix \code{Y} of size \code{n_pairs × n_celltypes}, where each
# entry is the distance between the two samples in that pair for a given cell type.
# Pairs involving a sample that is absent from a particular cell type are returned
# as \code{NA}, preserving the global pair layout for downstream modelling.
#
# @param cm.norm List of normalized count matrices per cell type
# @param dist what distance measure to use: 'cor' - Pearson's correlation, 'l2' - Euclidean distance, 'l1' - Manhattan distance
#' @param pair.model result of buildPairDesignMatrices()
#' @param sample.ids global sample IDs in the same order as rows of sample.metadata
#' @return A list with a single component:
#' \describe{
#'   \item{\code{Y}}{Numeric matrix of size \code{nrow(pair.model$pairs) × length(cm.norm)}.
#'     Rows correspond to global sample pairs; columns correspond to cell types
#'     (names taken from \code{names(cm.norm)}). Entries are distances for the
#'     requested metric, or \code{NA} if a given pair cannot be formed for that
#'     cell type (e.g. one or both samples are missing).}
#' }
#'
#' @seealso \code{\link{buildPairDesignMatrices}} for constructing the pair design
#' @keywords internal
estimateExpressionShiftsForCellType <- function( cm.norm, dist, pair.model, sample.ids) {
    # ---- basic checks ----
    if (!is.list(cm.norm))
        stop("cm.norm must be a list of count matrices per cell type.")
    if (missing(pair.model) || is.null(pair.model$pairs))
        stop("pair.model (from buildPairDesignMatrices) with $pairs is required.")
    if (missing(sample.ids))
        stop("sample.ids must be provided and must align with rows of sample.metadata.")
    
    idx <- pair.model$pairs
    if (!(is.matrix(idx) && ncol(idx) == 2L))
        stop("pair.model$pairs must be an n_pairs x 2 matrix of sample indices (i,j).")
    
    if (length(sample.ids) < max(idx))
        stop("sample.ids length is smaller than max(pair.model$pairs).")
    
    # pair names for rows of Y / dists (for printing)
    pair.names <- paste(sample.ids[idx[, "i"]], sample.ids[idx[, "j"]], sep = "__")
    
    # cell type names
    ctnames <- names(cm.norm)
    if (is.null(ctnames)) ctnames <- paste0("CT", seq_along(cm.norm))
    
    # ---- allocate Y: rows = pairs, cols = cell types ----
    Y <- matrix(NA_real_, nrow = nrow(idx), ncol = length(cm.norm),
                dimnames = list(pair.names, ctnames))
    
    # ---- loop over cell types ----
    for (t in seq_along(cm.norm)) {
        X <- cm.norm[[t]]    # samples x genes for this type (subset of samples)
        Xp <- X              # removed any PCA / gene selection
        
        # ensure rownames are sample IDs; needed for mapping
        if (is.null(rownames(Xp))) {
            stop("cm.norm[[", t, "]] has no rownames; cannot map to sample.ids.")
        }
        
        # (1) Distances — square matrix D over *local* rows of this type
        D <- NULL
        if (dist == "cor") {
            Xc <- as.matrix(Xp)
            n_rows <- nrow(Xc)
            if (is.null(n_rows) || n_rows < 2L) {
                D <- matrix(0, n_rows, n_rows,
                            dimnames = list(rownames(Xc), rownames(Xc)))
            } else {
                R <- stats::cor(t(Xc), use = "pairwise.complete.obs", method = "pearson")
                D <- 1 - R
                if (is.null(rownames(R))) {
                    rownames(D) <- colnames(D) <- rownames(Xc)
                }
            }
        } else if (dist %in% c("l2", "l1")) {
            Xd <- as.matrix(Xp)
            n_rows <- nrow(Xd)
            if (n_rows < 2L) {
                D <- matrix(0, n_rows, n_rows,
                            dimnames = list(rownames(Xd), rownames(Xd)))
            } else if (anyNA(Xd)) {
                D <- matrix(NA_real_, n_rows, n_rows,
                            dimnames = list(rownames(Xd), rownames(Xd)))
                diag(D) <- 0
                for (i in seq_len(n_rows - 1L)) {
                    xi <- Xd[i, ]
                    for (j in (i + 1L):n_rows) {
                        xj <- Xd[j, ]
                        if (anyNA(xi) || anyNA(xj)) {
                            d <- NA_real_
                        } else if (dist == "l2") {
                            d <- sqrt(sum((xi - xj)^2))
                        } else {
                            d <- sum(abs(xi - xj))
                        }
                        D[i, j] <- D[j, i] <- d
                    }
                }
            } else {
                method <- if (dist == "l2") "euclidean" else "manhattan"
                D <- as.matrix(stats::dist(Xd, method = method))
                if (is.null(rownames(D)) && !is.null(rownames(Xd))) {
                    rownames(D) <- colnames(D) <- rownames(Xd)
                }
            }
        } else {
            stop("Unknown distance: ", dist)
        }
        
        # ensure D is square and has rownames
        if (!is.matrix(D)) D <- as.matrix(D)
        dimD <- dim(D)
        if (length(dimD) != 2L || dimD[1] != dimD[2]) {
            stop("Distance is not a square matrix for cell type '", ctnames[t],
                 "': got ", paste(dimD, collapse = "x"))
        }
        if (is.null(rownames(D))) {
            stop("Distance matrix D for cell type '", ctnames[t],
                 "' has no rownames; cannot map to sample.ids.")
        }
        
        # (2) Vectorize using global pairs, mapping to local D indices via sample IDs
        Y[, t] <- vectorizeLowerTri(D, pairs = idx, sample.ids = sample.ids, row.ids = rownames(D))
    }
    
    list(Y = Y)        # all pairs x cell types (NA where sample missing in type)
    
}

#' Map a square distance matrix to a global pairwise layout
#'
#' This helper takes a sample–sample distance matrix \code{D} defined over a
#' subset of samples (e.g. those present for a given cell type) and extracts
#' distances for a set of **global pairs** specified by integer indices.
#' It returns a numeric vector of distances for those pairs, inserting NA if 
#' either member of the pair cannot be matched to a row in \code{D}.
#' @keywords internal
vectorizeLowerTri <- function(D, pairs, sample.ids, row.ids = rownames(D)) {
    # D: square distance matrix over *local* rows
    # pairs: n_pairs x 2 integer matrix with columns i,j (global sample indices)
    # sample.ids: length n_global, IDs in the same order as rows of sample.meta
    # row.ids: IDs corresponding to rows of D (subset of sample.ids)
    
    if (is.null(row.ids)) {
        stop("Distance matrix D must have rownames (sample IDs) to map pairs correctly.")
    }
    
    # Map global sample indices -> local row indices in D
    # global k -> sample.ids[k] -> match in row.ids
    global2local <- match(sample.ids, row.ids)  # length n_global, can be NA
    
    vapply(seq_len(nrow(pairs)), function(k) {
        gi <- pairs[k, 1]
        gj <- pairs[k, 2]
        li <- global2local[gi]
        lj <- global2local[gj]
        
        if (is.na(li) || is.na(lj)) {
            NA_real_              # this pair involves a sample missing in this cell type
        } else {
            D[li, lj]
        }
    }, numeric(1))
}

#' @keywords internal
joinExpressionShiftDfs <- function(dist.df.per.type, sample.groups) {
  dist.df.per.type %<>% .[!sapply(., is.null)]
  df <- names(dist.df.per.type) %>%
    lapply(function(n) cbind(dist.df.per.type[[n]], Type=n)) %>%
    do.call(rbind, .) %>%
    mutate(Condition=sample.groups[as.character(Var1)]) %>%
    na.omit()

  return(df)
}

#' @keywords internal
prepareJointExpressionDistance <- function(p.dist.per.type, sample.groups=NULL, return.dists=TRUE) {
  checkPackageInstalled(c("abind"), cran=TRUE)
  # bring to a common set of cell types
  common.types <- lapply(p.dist.per.type, colnames) %>% unlist() %>% unique()

  p.dist.per.type %<>% lapply(function(x) {
    y <- matrix(0,nrow=length(common.types),ncol=length(common.types));  # can set the missing entries to zero, as they will carry zero weights
    rownames(y) <- colnames(y) <- common.types;
    y[rownames(x),colnames(x)] <- x;
    ycct <- setNames(rep(0,length(common.types)), common.types);
    ycct[colnames(x)] <- attr(x, 'n.cells')
    attr(y, 'n.cells') <- ycct
    y
  }) # reform the matrix to make sure all cell type have the same dimensions

  x <- abind::abind(lapply(p.dist.per.type, function(x) {
    nc <- attr(x, 'n.cells')
    #wm <- (outer(nc,nc,FUN='pmin'))
    wm <- sqrt(outer(nc, nc, FUN = 'pmin'))
    return(x * wm)
  }), along = 3)

  # just the weights (for total sum of weights normalization)
  y <- abind::abind(lapply(p.dist.per.type, function(x) {
    nc <- attr(x, 'n.cells')
    sqrt(outer(nc, nc, FUN = 'pmin'))
  }), along = 3)

  # normalize by total weight sums
  xd <- apply(x, c(1, 2), sum) / apply(y, c(1, 2), sum)

  if (return.dists)
    return(xd)

  cross.factor <- outer(sample.groups[rownames(xd)], sample.groups[colnames(xd)], '==')
  diag(xd) <- NA # remove self pairs
  # restrict
  xd[!cross.factor] <- NA
  if (!any(!is.na(xd)))
    return(NULL)
  xmd2 <- na.omit(reshape2::melt(xd))
  xmd2 <- na.omit(xmd2)
  xmd2$type1 <- sample.groups[as.character(xmd2$Var1)]
  xmd2$type2 <- sample.groups[as.character(xmd2$Var2)]

  return(xmd2)
}

#' Filter cell types for paired analysis using paired design coverage
#'
#' This replaces the old `filterCellTypesByNSamples()` logic in a *paired*
#' differential analysis context.
#'
#' It keeps only those cell types that:
#'   1. Have enough cells per sample (`min.cells.per.sample`) AND
#'   2. Are observed in at least `min.samp.per.type` *distinct samples* that
#'      actually participate in the paired contrast of interest.
#'
#' How "participate in the paired contrast" is determined:
#'   - We look at `pairDesign$model$core.rows`, which is a logical vector
#'     (length = number of pair rows in the paired design) telling us which
#'     *pairs of samples (i,j)* contribute to the core contrast `X`.
#'   - We then mark any sample that appears in at least one such "core" pair
#'     as a "usable" sample.
#'
#' Steps performed internally:
#'   1. Extract the set of usable samples (based on core pairs).
#'   2. Build a table of how many single cells of each `cell.type` each `sample.id`
#'      contributed (`Freq`).
#'   3. Keep only those (Type,Sample) combos where:
#'        - `Freq >= min.cells.per.sample`, and
#'        - `Sample` is among usable samples.
#'   4. For each Type, count how many distinct usable samples survive. If this
#'      count is at least `min.samp.per.type`, we keep that Type.
#'
#' The output can be fed into downstream preprocessing to drop unsupported
#' cell types before building per-type matrices.
#'
#' @param cell.groups factor/character vector of length = total cells, giving
#'        the cell type (cluster / annotation) for each cell.
#' @param sample.per.cell character or factor vector of same length as
#'        `cell.groups`, giving which biological sample each cell came from.
#' @param pairDesign result of `buildPairDesignMatrices()`. We assume:
#'        - `pairDesign$pairs`: integer matrix (n_pairs x 2), each row is the
#'          indices `(i,j)` of the two samples in that pair, 1-based and
#'          referring to rows of the original `sample.meta`.
#'        - `pairDesign$model$core.rows`: logical vector of length n_pairs;
#'          TRUE where that pair contributes to the tested contrast (i.e. has
#'          non-negligible X signal after contrast splitting).
#' @param sample.ids character vector of length `nrow(sample.meta)` in the same
#'        row order that was given to `buildPairDesignMatrices()`. So if
#'        `sample.meta` had rownames, you usually pass `rownames(sample.meta)`.
#'        These IDs must match the values used in `sample.per.cell`.
#' @param min.cells.per.sample integer. Minimum number of cells of a given type
#'        that must appear in a given sample for that (Type,Sample) combo to count.
#' @param min.samp.per.type integer. Minimum number of *distinct usable samples*
#'        in which a type must appear (above the per-sample threshold) in order
#'        for that type to be kept.
#' @param use.core.rows logical (default TRUE). If TRUE, only pairs with
#'        `core.rows==TRUE` are used to establish which samples are "usable".
#'        If FALSE, *all* pairs in `pairDesign$pairs` are considered usable.
#' @param verbose logical. If TRUE, emit messages about dropped cell types.
#'
#' @return A list with:
#'   - `freq.table`: data.frame with columns
#'        `Type`, `Sample`, `Freq`, `Usable`
#'     after applying the per-sample coverage threshold.
#'   - `kept.types`: character vector of cell types that survive filtering.
#'   - `kept.by.sample`: named list. For each surviving sample ID, a unique
#'        character vector of the kept types that sample supports.
#'
#' Typical usage:
#' \preformatted{
#' out <- filterCellTypesByCoveragePairs(
#'   cell.groups         = cell.groups,
#'   sample.per.cell     = sample.per.cell,
#'   pairDesign          = pairDesign,
#'   sample.ids          = rownames(sample.meta),
#'   min.cells.per.sample= 10,
#'   min.samp.per.type   = 2,
#'   use.core.rows       = TRUE,
#'   verbose             = TRUE
#' )
#'
#' ## Keep only out$kept.types when building per-type expression matrices.
#' }
#'
#' Rationale:
#'   - We no longer assume a 2-condition factor like "Condition".
#'   - We only keep types with enough replication across biologically distinct
#'     samples that actually drive the paired contrast (i.e. show up in core pairs).
#'
#' @export
filterCellTypesByCoveragePairs <- function(cell.groups, sample.per.cell, pairDesign, sample.ids,
                                           min.cells.per.sample, min.samp.per.type, use.core.rows = TRUE,
                                           verbose = TRUE) {
  # ---- basic checks ----
  if (length(cell.groups) != length(sample.per.cell)) {
    stop("cell.groups and sample.per.cell must have the same length (one entry per cell).")
  }
  if (!is.list(pairDesign) ||
      is.null(pairDesign$pairs) ||
      is.null(pairDesign$core.rows)) {
    stop("pairDesign must be the full list returned by buildPairDesignMatrices() ",
         "and must include $pairs and $core.rows.")
  }
  pairs.mat <- pairDesign$pairs
  if (!(is.matrix(pairs.mat) && ncol(pairs.mat) == 2L)) {
    stop("pairDesign$pairs must be an n_pairs x 2 integer matrix of sample indices.")
  }
  n.pairs <- nrow(pairs.mat)
  core.rows <- pairDesign$core.rows
  if (!is.null(core.rows) && length(core.rows) != n.pairs) {
    stop("pairDesign$core.rows length does not match nrow(pairDesign$pairs).")
  }
  if (length(sample.ids) < max(pairs.mat)) {
    stop("sample.ids does not cover all indices mentioned in pairDesign$pairs.")
  }
  
  # ---- 1. determine usable samples from the paired design ----
  if (!n.pairs) {
    if (verbose) {
      message("No pairs in pairDesign$pairs; returning empty filter result.")
    }
    return(list(
      freq.table     = data.frame(Type=character(0), Sample=character(0),
                                  Freq=integer(0), Usable=logical(0),
                                  stringsAsFactors = FALSE),
      kept.types     = character(0),
      kept.by.sample = list()
    ))
  }
  
  if (use.core.rows && !is.null(core.rows)) {
    keep.pair.rows <- which(core.rows)
  } else {
    keep.pair.rows <- seq_len(n.pairs)
  }
  
  if (!length(keep.pair.rows)) {
    if (verbose) {
      message("No informative pairs (core.rows is empty TRUE set); all types dropped.")
    }
    return(list(
      freq.table     = data.frame(Type=character(0), Sample=character(0),
                                  Freq=integer(0), Usable=logical(0),
                                  stringsAsFactors = FALSE),
      kept.types     = character(0),
      kept.by.sample = list()
    ))
  }
  
  sample.idx.used <- unique(as.integer(pairs.mat[keep.pair.rows, , drop = FALSE]))
  usable.samples  <- unique(sample.ids[sample.idx.used])
  
  # ---- 2. build per-(Type,Sample) cell counts ----
  # coerce to plain factors/chars
  cell.types.vec     <- droplevels(factor(cell.groups))
  sample.per.cell.vec<- as.character(sample.per.cell)
  
  # table(Type, Sample)
  freq.table <- table(Type = cell.types.vec,
                      Sample = sample.per.cell.vec)
  freq.table <- as.data.frame(freq.table, stringsAsFactors = FALSE)
  
  # ---- 3. enforce per-sample minimum coverage and "sample is usable" ----
  # keep only Type/Sample combos with enough cells
  freq.table <- freq.table[freq.table$Freq >= min.cells.per.sample, , drop = FALSE]
  if (!nrow(freq.table)) {
    if (verbose) {
      message("No (Type,Sample) pairs pass min.cells.per.sample in paired context.")
    }
    return(list(
      freq.table     = transform(freq.table, Usable = logical(0)),
      kept.types     = character(0),
      kept.by.sample = list()
    ))
  }
  
  # mark which Sample entries are actually usable for the contrast
  freq.table$Usable <- freq.table$Sample %in% usable.samples
  
  # ---- 4. count usable samples per Type ----
  type.sample.split <- split(freq.table$Sample[freq.table$Usable],
                             freq.table$Type[freq.table$Usable])
  usable.counts <- vapply(type.sample.split,
                          function(sv) length(unique(sv)),
                          integer(1))
  
  kept.types <- names(usable.counts)[usable.counts >= min.samp.per.type]
  kept.types <- kept.types[!is.na(kept.types)]
  
  # produce kept.by.sample for convenience
  keep.mask <- freq.table$Usable & freq.table$Type %in% kept.types
  kept.by.sample <- split(freq.table$Type[keep.mask],
                          freq.table$Sample[keep.mask])
  kept.by.sample <- lapply(kept.by.sample, function(v) unique(as.character(v)))
  
  # ---- 5. messaging ----
  if (verbose) {
    removed.types <- setdiff(levels(cell.types.vec), kept.types)
    if (length(removed.types)) {
      message(
        "Excluding cell types in paired context: ",
        paste(removed.types, collapse = ", "),
        " (not enough distinct usable samples with >= ",
        min.cells.per.sample, " cells)"
      )
    }
  }
  
  # ---- 6. return ----
  list(
    freq.table     = freq.table,
    kept.types     = kept.types,
    kept.by.sample = kept.by.sample
  )
}



#' Prepare per-cell-type expression matrices for pairwise distance estimation
#'
#' This function filters cells, samples, and genes, then builds per-cell-type
#' sample × gene matrices that are normalized and aligned across samples. It is
#' the main preprocessing step before computing pairwise expression distances.
#'
#' Steps performed internally:
#'
#'   1. (Optional) Filter cell types and samples using the paired design:
#'        - If `keep.all = FALSE`, call `filterCellTypesByCoveragePairs()` to:
#'            * restrict to samples that participate in informative pairs
#'              (via `pair.model`), and
#'            * keep only cell types that appear in at least
#'              `min.cells.per.sample` cells per sample and in at least
#'              `min.samp.per.type` samples.
#'        - The original list `cms` is subset to `cms.filt`, with each sample
#'          retaining only the kept cell types.
#'        - If `keep.all = TRUE`, no cell-type filtering is done and
#'          `cms.filt <- cms`.
#'   2. Collect all cell names from the filtered matrices and drop unused
#'      levels in `cell.groups` accordingly.
#'   3. (Optional) Filter genes across samples:
#'        - If `genes` is `NULL`, for each sample matrix in `cms.filt`:
#'            * binarize counts to presence/absence (`> 1`),
#'            * compute per-gene mean across cells, and
#'            * keep genes with mean > `min.gene.frac`.
#'        - A consensus gene set is formed by keeping genes that pass this
#'          threshold in a sufficient fraction of samples.
#'   4. Collapse counts by cell type and align genes:
#'        - For each sample, call `collapseCellsByType()` to obtain a cell-type
#'          × gene matrix (one row per cell type present in that sample).
#'        - Use `sccore::extendMatrix()` to ensure that all sample matrices
#'          have the same gene set (columns), and reorder columns to match
#'          the final `genes` vector.
#'   5. Build per-cell-type normalized matrices:
#'        - For each cell type `ct` in `all.types`:
#'            * For each sample in `cms.filt`:
#'                - If the sample matrix is valid and contains `ct`, extract the
#'                  corresponding row (cell-type profile).
#'                - If the sample is valid but `ct` is missing, create a
#'                  1 × genes row filled with `NA` for that cell type.
#'                - If a sample entry is `NULL` or has no columns, it is skipped.
#'            * Bind all non-NULL rows into a single matrix: samples × genes.
#'            * Normalize each sample (row) by its total count:
#'                - compute row sums (ignoring `NA`),
#'                - divide by `pmax(1, row sum)` to avoid division by zero,
#'                - apply log-transform: `log10(norm * 1e3 + 1)`.
#'            * Assign row names to the matrix using the names of valid samples
#'              in `cms.filt`.
#'        - This produces one normalized matrix per cell type; samples that lack
#'          a given cell type will have `NA` values in that cell type’s matrix.
#'   6. Return a list containing:
#'        - `cm.per.type`: a named list (one entry per cell type), where each
#'          element is a samples × genes normalized matrix suitable for
#'          downstream distance estimation.
#'
#' @param cms List of per-sample count matrices (rows = cells, columns = genes).
#' @param cell.groups Factor or character vector giving the cell type for each
#'   cell (names must match cell row names in `cms`).
#' @param sample.per.cell Factor or character vector giving the sample ID for
#'   each cell (same length/order as `cell.groups`).
#' @param pair.model Output of `buildPairDesignMatrices()`, used to determine
#'   which samples participate in informative pairs.
#' @param sample.ids Character vector of global sample IDs, in the same order as
#'   the sample metadata used to build `pair.model`.
#' @param keep.all Logical; if `TRUE`, skip the paired design–based filtering of
#'   cell types and samples and keep all input cells (including all factor levels).
#' @param min.cells.per.sample Minimum number of cells per (cell type, sample)
#'   combination to consider that combination usable.
#' @param min.samp.per.type Minimum number of samples that must pass the
#'   per-sample cell-count filter for a cell type to be retained.
#' @param min.gene.frac Minimum mean (after binarization) required for a gene
#'   to be kept when computing the consensus gene set.
#' @param genes Optional character vector of genes to keep. If supplied, the
#'   automatic gene filtering step is skipped and matrices are extended to this
#'   gene set.
#' @param verbose Logical; if `TRUE`, print progress and filtering messages.
#'
#' @return A list with one component:
#'   \describe{
#'     \item{cm.per.type}{Named list of normalized sample × gene matrices, one
#'       per cell type. Rows are samples; columns are genes. Entries can be `NA`
#'       when a given sample does not contain that cell type or when normalization
#'       encounters missing values.}
#'   }
#'
#' @keywords internal
filterExpressionDistanceInput <- function(
  cms, cell.groups, sample.per.cell, pair.model, sample.ids, keep.all=TRUE,
  min.cells.per.sample=10, min.samp.per.type=2, min.gene.frac=0.01,
  genes=NULL, verbose=FALSE
) {
  stopifnot(is.list(cms), length(cms) > 0)
  all.samples <- names(cms)

  if (!keep.all) {
    cell.names <- lapply(cms, rownames) %>% unlist()
    freq.table <- filterCellTypesByCoveragePairs(cell.groups[cell.names], sample.per.cell[cell.names], pair.model, sample.ids, min.cells.per.sample, min.samp.per.type, verbose=verbose)
    filt.types.per.samp <- freq.table$kept.by.sample # Changes made here
    cms.filt <- names(filt.types.per.samp) %>% sn() %>% lapply(function(n) {
      cms[[n]] %>% .[cell.groups[rownames(.)] %in% filt.types.per.samp[[n]], , drop=FALSE]
    })
    names(cms.filt) <- names(filt.types.per.samp)
  } else {
    cms.filt <- cms
  }

  cell.names <- lapply(cms.filt, rownames) %>% unlist()

  # ---- Gene filtering across samples ---- (KEPT this gene filtering)
  if (is.null(genes)) {
    genes <- lapply(cms.filt, function(cm) {
      cm@x <- 1 * (cm@x > 1)
      names(which(colMeans(cm) > min.gene.frac))
    }) %>%
      unlist() %>% table() %>% {. / length(cms.filt) > 0.1} %>% which() %>% names()
  }

  # ---- Collapse by cell type and align genes ----
  cms.filt %<>% lapply(collapseCellsByType, groups=cell.groups, min.cell.count=1)
  cms.filt %<>% lapply(sccore::extendMatrix, genes) %>% lapply(`[`, , genes, drop=FALSE)

  # ---- Build per-cell-type matrices (kept NORM only) ----
  cell.groups <- droplevels(cell.groups[cell.names])
  all.types <- levels(cell.groups)

  cms.filt <- cms.filt[all.samples]

  cm.per.type <- sccore::sn(all.types) %>% lapply(function(ct) {
    # norm: row present -> take it; missing -> NA row (as before)
    rows.norm <- lapply(cms.filt, function(x) {
      # skip NULL/non-matrix entries
      if (is.null(x) || is.null(ncol(x))) {
        return(NULL)
      }

      if (ct %in% rownames(x)) {
        as.matrix(x[ct, , drop=FALSE]) 
      } else {
        matrix(NA_real_, nrow=1, ncol=ncol(x), dimnames=list(ct, colnames(x)))
      }
    })
    rows.norm <- Filter(Negate(is.null), rows.norm)
    mat <- do.call(rbind, rows.norm)                   # samples x genes
    denom <- pmax(1, rowSums(mat, na.rm=TRUE))
    mat <- mat / denom
    mat <- log10(mat * 1e3 + 1)
    # set rownames only for the non-NULL entries
    valid <- !vapply(cms.filt, function(x) is.null(x) || is.null(ncol(x)), logical(1))
    rownames(mat) <- names(cms.filt)[valid]
    mat
  })
  names(cm.per.type) <- all.types
  return(list("cm.per.type" = cm.per.type))       # normalized (use everywhere downstream)
}


#' @keywords internal
estimateExplainedVariance <- function(cm, sample.groups) {
  checkPackageInstalled("matrixStats", cran=TRUE)
  spg <- rownames(cm) %>% split(droplevels(as.factor(sample.groups[.])))
  if (length(spg) == 1){
    return(NULL)
  }

  sapply(spg, function(spc) matrixStats::colVars(cm[spc,,drop=FALSE]) * (length(spc) - 1)) %>%
    rowSums(na.rm=TRUE) %>%
    {1 - (. / (matrixStats::colVars(cm) * (nrow(cm) - 1)))} %>%
    setNames(colnames(cm))
}


## Generic grouping for pair-level design matrices, used in R2 estimation per variable across cell types (updated for new pair design)
## - collapses all "<var>_pair*" columns into one group per <var>
##   (and prefers any "<var>_pair_contrast" column if present)
## - groups numeric pair columns "pair_<var>_(mean|diff)" into one group "pair_<var>"
## - keeps "(Intercept)" if present
## - anything else stays as-is (unless include.other=TRUE, then grouped under "Other")
makeGroupsPair <- function(M, include.other = FALSE) {
    stopifnot(!is.null(colnames(M)))
    cn <- colnames(M)
    groups <- list()
    
    ## 1) Intercept
    if ("(Intercept)" %in% cn) {
        groups$Intercept <- "(Intercept)"
    }
    
    ## 2) Factor pair terms: "<var>_pair*"
    pair.terms <- grep("_pair", cn, value = TRUE)
    if (length(pair.terms)) {
        # extract variable name before "_pair"
        varnames <- sub("_pair.*$", "", pair.terms)
        for (v in unique(varnames)) {
            cols <- pair.terms[varnames == v]
            # if there's a collapsed contrast, prefer that
            contrast.cols <- grep("_pair_contrast$", cols, value = TRUE)
            if (length(contrast.cols)) {
                groups[[v]] <- contrast.cols
            } else {
                groups[[v]] <- cols
            }
        }
    }
    
    ## 3) Numeric pair terms: "pair_<var>_(mean|diff)"
    num.pair <- grep("^pair_[A-Za-z0-9.]+_(mean|diff)$", cn, value = TRUE)
    if (length(num.pair)) {
        base <- sub("^pair_([A-Za-z0-9.]+)_(mean|diff)$", "\\1", num.pair)
        for (v in unique(base)) {
            cols <- num.pair[base == v]
            gname <- paste0("pair_", v)
            if (gname %in% names(groups)) {
                groups[[gname]] <- unique(c(groups[[gname]], cols))
            } else {
                groups[[gname]] <- cols
            }
        }
    }
    
    ## 4) Leftovers
    used <- unlist(groups, use.names = FALSE)
    leftovers <- setdiff(cn, used)
    if (length(leftovers)) {
        if (include.other) {
            groups$Other <- leftovers
        } else {
            for (lf in leftovers) groups[[lf]] <- lf
        }
    }
    
    groups
}




#' Extract contrast-specific pairwise expression shifts for plotting
#'
#' This function takes the output of the linear model/permutation fit and the
#' pairwise distance matrix, and constructs contrast-specific **expression
#' shifts** for each pair and cell type for core sample-pair rows (cross-group). 
#' It supports both block permutations and Freedman–Lane residualization and 
#' returns tidy data frames suitable for
#' visualization and permutation-background plots. 
#' It handles factor and numeric variables separately for centering across cell types.
#' 
#' Factor-based contrasts (e.g., Group_pair) are centered by decomposing the contrast into 
#' positive- and negative-weight factor levels. For each cell type, the model computes a 
#' weighted average of the fitted values across all negative-weight levels to form a baseline, 
#' and expression shifts are defined as the fitted value for each positive-weight pair minus 
#' this baseline. For continuous (numeric) contrasts (e.g., pair_age_diff, pair_age_mean), 
#' centering is performed around a scalar reference value x0. The reference is chosen in the 
#' following order: (1) an explicit numeric anchor provided by numeric_ref_used (via x0.override), 
#' (2) automatic heuristics—pair_*_diff contrasts are centered at 0 (no difference), while pair_*_mean 
#' contrasts are centered at the mean or provided reference of the underlying variable, and
#' (3) if no numeric baseline is available, a fallback factor-based centering approach uses a factor 
#' contrast to compute a weighted average of the numeric variable (as before). 
#' Continuous shifts are therefore slopes of fitted values with respect to the variable, 
#' evaluated at the centered predictor x-x0. 
#'
#' Steps performed internally:
#'   1. Choose the appropriate design and fitted values:
#'        - If `perm.method = "block"`:
#'            * Call `extractFitsBlock()` to obtain partial fits and full fits
#'              based on the full design `F`.
#'            * Use `design.mat$contrast.F` and `design.mat$F`.
#'        - If `perm.method = "freedman-lane"`:
#'            * Call `extractFitsFL()` to obtain partial fits based on the core
#'              design `X` and residualized response.
#'            * Use `design.mat$contrast.X` and `design.mat$X`.
#'   2. Reconstruct the coefficient matrix:
#'        - If `res$coef` is provided and has the expected length, reshape it
#'          into a matrix with:
#'            * rows = columns of `F` or `X` (depending on `perm.method`),
#'            * columns = cell types (columns of `p.dist`).
#'        - This matrix (`coef.mat`) is later used for continuous contrasts.
#'   3. Parse the contrast:
#'        - Use `getContrastInfo()` to classify the contrast as:
#'            * **factor-like** (e.g., weights over pair-factor levels), or
#'            * **continuous** (e.g., a numeric pair covariate).
#'        - For continuous contrasts, attempt to:
#'            * infer a numeric baseline `x0.override` from the paired variable
#'              name (e.g. `pair_age_diff` → baseline 0),
#'            * or from `design.mat$numeric_ref_used` when available,
#'            * otherwise fall back to factor-based centering rules.
#'   4. Call `extractContrastDeltas()`:
#'        - Pass in:
#'            * `partial.fit` (contrast-specific fitted values),
#'            * `pair.meta` (pair-level metadata from `design.mat`),
#'            * the parsed contrast vector,
#'            * optional `block.vars` (for block-level summaries),
#'            * `coef.mat` (for continuous contrasts),
#'            * `center.contrast` and/or `x0.override` (for centering).
#'        - Receive pairwise shifts (and optional block summaries) per cell type.
#'   5. Tidy the pairwise shifts:
#'        - Convert the `delta$shifts` matrix (pairs × cell types) into a long
#'          data frame with columns:
#'            * `pair` (rownames),
#'            * `celltype`,
#'            * `shifts` (numeric).
#'        - Filter out non-finite values (`NA`, `NaN`, `Inf`).
#'   6. Process permutation statistics (if present):
#'        - If `res$stats.perm` is not `NULL`, reshape it into a long data frame
#'          of permutation statistics per cell type.
#'        - If `res$stat.obs` is not `NULL`, store the observed statistic per
#'          cell type in a small data frame.
#'   7. Subset covariates and return:
#'        - Align `design.mat$pair.meta` rows to the shifts matrix using
#'          `rownames(delta$shifts)` and store as `pair.covariates` (used for cov.plot.keys).
#'        - Return a list containing:
#'            * `df.shifts` — per-pair, per-celltype shifts,
#'            * `pair.covariates` — aligned pair-level metadata,
#'            * `dist.type` — inferred centering type or `"continuous"`,
#'            * `contrast` — the contrast vector,
#'            * optionally `df.blocks`, `df.perm`, `df.perm.obs`, and `x.center`.
#'
#' NA handling:
#'   - Any non-finite values in the shifts or permutation statistics are
#'     removed from the returned data frames.
#'   - Rows in `pair.meta` that cannot be aligned to `yhat.all` will cause
#'     an error upstream in `extractContrastDeltas()`.
#'
#' @param res Output from the permutation/linear model fitting function
#'   (`performLMPermutations()`), containing coefficients, residuals,
#'   and optional permutation statistics.
#' @param p.dist Output of `estimateExpressionShiftsForCellType()`, containing
#'   the pairwise distance matrix `Y`.
#' @param design.mat Paired design object, typically the result of
#'   `buildPairDesignMatrices()`, containing `F`, `X`, `pair.meta`,
#'   `contrast.F`, `contrast.X`, and optionally `numeric_ref_used`.
#' @param perm.method Character; either `"freedman-lane"` or `"block"`,
#'   specifying which fitted values to extract and which contrast space
#'   (F vs X) to work in.
#' @param block.vars Optional character vector of column names in
#'   `design.mat$pair.meta` to define blocks for summarizing shifts.
#'
#' @return A list with components:
#'   \describe{
#'     \item{df.shifts}{Long-format data frame of per-pair, per-celltype
#'       contrast-specific shifts.}
#'     \item{pair.covariates}{Pair-level metadata aligned to `df.shifts`.}
#'     \item{dist.type}{Character string describing the centering mode
#'       (`"shift"`, `"total"`, `"var"`, `"custom"`, or `"continuous"`).}
#'     \item{contrast}{The contrast vector used.}
#'     \item{df.blocks}{(Optional) block-wise summary of shifts, if
#'       `block.vars` was supplied.}
#'     \item{df.perm}{(Optional) permutation statistics in long format.}
#'     \item{df.perm.obs}{(Optional) observed test statistics per cell type.}
#'     \item{x.center}{(Optional) scalar numeric baseline used for continuous
#'       contrasts.}
#'   }
#'
#' @keywords internal
extractPairwiseShifts <- function(res,design.mat,
                                  perm.method = c("freedman-lane", "block"),
                                  block.vars = NULL) {
    perm.method <- match.arg(perm.method)
    
    if (perm.method == "block") {
        blk <- extractFitsBlock(res, res$sample.distances, design.model = design.mat)
        partial.fit  <- blk$partial
        contrast.vec <- design.mat$contrast.F
        F <- as.matrix(design.mat$F)
        
        coef.mat <- NULL
        if (!is.null(res$coef)) {
            expect <- ncol(F) * ncol(res$sample.distances)
            if (length(res$coef) == expect) {
                coef.mat <- matrix(res$coef,
                                   nrow = ncol(F),
                                   dimnames = list(colnames(F), colnames(res$sample.distances)))
            }
        }
        
    } else if (perm.method == "freedman-lane") {
        partial.fit  <- extractFitsFL(res, p.dist, design.model = design.mat)
        contrast.vec <- design.mat$contrast.X
        X <- as.matrix(design.mat$X)
        
        coef.mat <- NULL
        if (!is.null(res$coef)) {
            expect <- ncol(X) * ncol(res$sample.distances)
            if (length(res$coef) == expect) {
                coef.mat <- matrix(res$coef,
                                   nrow = ncol(X),
                                   dimnames = list(colnames(X), colnames(res$sample.distances)))
            }
        }
        
    } else {
        stop("Unknown model type: ", perm.method)
    }
    
    ci <- getContrastInfo(contrast.vec)
    center.contrast <- ci$center
    x0.override <- NULL   # new: numeric baseline for continuous contrasts
    
    ## --- continuous contrasts: pick x0 using numeric_ref_used when possible --- # //TODO discuss for numeric contrasts
    if (ci$kind == "continuous") {
        var <- ci$var  # e.g. "pair_age_diff" or "pair_age_mean"
        
        # Heuristic for pair numerics: pair_<v>_(mean|diff)
        m  <- regexec("^pair_([A-Za-z0-9.]+)_(mean|diff)$", var)
        mt <- regmatches(var, m)[[1]]
        
        if (length(mt) == 3L) {
            base <- mt[2]     # "age"
            kind <- mt[3]     # "mean" or "diff"
            
            if (kind == "diff") {
                # natural: baseline is zero difference
                x0.override <- 0
            } else if (kind == "mean") {
                # natural: baseline is numeric_ref_used[[base]] if present
                if (!is.null(design.mat$numeric_ref_used) &&
                    base %in% names(design.mat$numeric_ref_used)) {
                    x0.override <- design.mat$numeric_ref_used[[base]]
                } else {
                    # leave NULL here; we'll fall back to mean(x) inside extractContrastDeltas()
                }
            }
        }
        
        # if we still don't have a numeric baseline, fall back to the old
        # factor-centering mechanism via center.contrast
        if (is.null(center.contrast)) {
            for (v in list(design.mat$contrast.F, design.mat$contrast.X)) {
                if (is.null(v)) next
                v.center <- attr(v, "center")
                if (!is.null(v.center)) { center.contrast <- v.center; break }
                if (any(grepl("=", names(v), fixed = TRUE))) {
                    center.contrast <- v
                    break
                }
            }
            # note: if center.contrast is still NULL and x0.override is NULL,
            # extractContrastDeltas() will error with a clear message.
        }
    }
    
    delta <- extractContrastDeltas(
        yhat.all        = partial.fit,      # contrast-specific fits
        pair.meta       = design.mat$pair.meta,
        contrast.vec    = contrast.vec,
        block.vars      = block.vars,
        coef.mat        = coef.mat,
        center.contrast = center.contrast,
        x0.override     = x0.override       
    )
    
    df.shifts <- as.data.frame(delta$shifts) |>
        tibble::rownames_to_column("pair") |>
        tidyr::pivot_longer(-pair, names_to = "celltype", values_to = "shifts") |>
        dplyr::filter(is.finite(shifts))
    
    stats.perm <- if (!is.null(res$stats.perm)) res$stats.perm else NULL
    stat.obs   <- if (!is.null(res$stat.obs))   res$stat.obs   else NULL
    df.perm     <- NULL
    df.perm.obs <- NULL
    
    if (!is.null(stats.perm)) {
        ct <- colnames(stats.perm)
        df.perm <- as.data.frame(stats.perm) |>
            tidyr::pivot_longer(tidyselect::all_of(ct),
                                names_to = "celltype",
                                values_to = "perm_stat") |>
            dplyr::filter(is.finite(perm_stat))
        if (!is.null(stat.obs)) {
            df.perm.obs <- data.frame(celltype = ct,
                                      obs      = as.numeric(stat.obs),
                                      stringsAsFactors = FALSE)
        }
    }
    
    out <- list(
        df.shifts       = df.shifts,
        pair.covariates = design.mat$pair.meta[rownames(delta$shifts), , drop = FALSE],
        dist.type       = delta$inferred,
        contrast        = contrast.vec
    )
    if (!is.null(delta$delta.block)) out$df.blocks   <- delta$delta.block
    if (!is.null(df.perm))           out$df.perm     <- df.perm
    if (!is.null(df.perm.obs))       out$df.perm.obs <- df.perm.obs
    if (!is.null(delta$x.center))    out$x.center    <- delta$x.center
    
    out
}


#' Extract contrast-specific shifts from fitted values
#'
#' Given contrast-specific fitted values per pair and cell type, this function
#' computes **expression shifts** for:
#'   - factor-like contrasts (e.g., AB vs AA/BB composition; set by dist.type), and
#'   - continuous contrasts (e.g., a paired numeric covariate),
#' using an appropriate centering rule. Optionally, it also computes
#' block-level summaries.
#'
#' Steps performed internally:
#'   1. Align fitted values to pair metadata:
#'        - Check that both `yhat.all` and `pair.meta` have row names.
#'        - Match `rownames(yhat.all)` to `rownames(pair.meta)` and subset
#'          `pair.meta` to the same order.
#'        - Error if any rows cannot be aligned.
#'   2. Parse the contrast:
#'        - Use `getContrastInfo(contrast.vec)` to determine:
#'            * `kind = "factor"` — weights over factor levels stored in
#'              `ci$w`, with `ci$var` naming the factor column in `pair.meta`.
#'            * `kind = "continuous"` — a single numeric variable `ci$var`.
#'   3. Factor contrast path (`kind == "factor"`):
#'        - Identify positive-weight and negative-weight levels of
#'          `pair.meta[[ci$var]]`.
#'        - For each negative level, compute the column-wise mean fitted value.
#'        - Build a weighted negative baseline as a weighted sum of these
#'          means (with weights `-ci$w[neg]`), normalized by the sum of
#'          positive weights.
#'        - For rows belonging to positive levels, compute shifts as:
#'            * fitted value − baseline (per pair, per cell type).
#'        - If `block.vars` is supplied:
#'            * group pairs by the specified block columns in `pair.meta`,
#'            * recompute baselines within each block, and
#'            * compute block-wise mean shifts for each cell type.
#'   4. Continuous contrast path (`kind == "continuous"`):
#'        - Extract the numeric predictor `x` from `pair.meta[[ci$var]]`.
#'        - Ensure `coef.mat` contains a row for `ci$var`, giving a slope per
#'          cell type.
#'        - Choose a scalar baseline `x0`:
#'            * if `x0.override` is provided, use it directly;
#'            * otherwise, apply heuristics for `pair_<var>_(mean|diff)`:
#'                - `*_diff` → baseline 0,
#'                - `*_mean` → mean(x), unless overridden;
#'            * if still unresolved, use a factor-based centering rule via
#'              `center.contrast` and `contrastCenterX0()`.
#'        - Compute centered predictor values: `x.c = x - x0`.
#'        - Multiply `x.c` by the slopes in `coef.mat[var, ]` to obtain
#'          pairwise shifts per cell type.
#'        - If `block.vars` is supplied, compute block-wise mean shifts by
#'          averaging over pairs within each block.
#'   5. Return a list with:
#'        - `shifts`: matrix of pairwise shifts (pairs × cell types),
#'        - `delta.block`: optional block-wise summary data frame,
#'        - `inferred`: `"shift"`, `"total"`, `"var"`, `"custom"`, or `"continuous"`,
#'        - `x.center`: scalar `x0` used for continuous contrasts (if applicable).
#' NA handling:
#'   - Means and baselines are computed with `na.rm = TRUE`, so missing
#'     fitted values do not break the computation but may propagate as
#'     `NA` where no valid observations remain.
#'   - If a factor level contains no valid rows, its contribution to the
#'     baseline is set to an `NA` vector, which may lead to `NA` shifts.
#'
#' @param yhat.all Matrix of fitted values (pairs × cell types) corresponding
#'   to the contrast of interest (e.g. partial fits from `extractFitsBlock()`
#'   or `extractFitsFL()`).
#' @param pair.meta Data frame of pair-level metadata, with row names matching
#'   those of `yhat.all`.
#' @param contrast.vec Named numeric contrast vector, as produced by the
#'   design constructors (factor or continuous type).
#' @param block.vars Optional character vector of column names in `pair.meta`
#'   used to define blocks for summary statistics.
#' @param tol Numeric tolerance used when inferring centering type.
#' @param coef.mat Optional numeric matrix of coefficients with:
#'   rows = term names, columns = cell types. Required for continuous contrasts
#'   (must contain a row named `ci$var`).
#' @param center.contrast Optional factor-like contrast used for centering
#'   continuous predictors when `x0.override` is not provided.
#' @param x0.override Optional scalar numeric baseline for continuous
#'   contrasts; if provided, overrides all other centering rules.
#'
#' @return A list with components:
#'   \describe{
#'     \item{shifts}{Matrix of pairwise shifts (pairs × cell types).}
#'     \item{delta.block}{(Optional) data frame of block-wise shifts.}
#'     \item{inferred}{Character string describing the centering or contrast
#'       type.}
#'     \item{x.center}{(For continuous contrasts) scalar baseline `x0` used.}
#'   }
#'
#' @keywords internal
extractContrastDeltas <- function(yhat.all, pair.meta, contrast.vec,
                                  block.vars = NULL, tol = 1e-8,
                                  coef.mat = NULL, center.contrast = NULL,
                                  x0.override = NULL) {
    ci <- getContrastInfo(contrast.vec)
    
    # Align pair.meta to yhat rows
    if (is.null(rownames(yhat.all)))
        stop("yhat.all must have rownames to align with pair.meta.")
    if (is.null(rownames(pair.meta)))
        stop("pair.meta must have rownames to align with yhat.all.")
    pos.pm <- match(rownames(yhat.all), rownames(pair.meta))
    if (any(is.na(pos.pm)))
        stop("Could not align pair.meta to yhat rows; check rownames.")
    pm.aligned <- pair.meta[pos.pm, , drop = FALSE]
    
    ## ----- FACTOR CONTRAST PATH -----
    if (ci$kind == "factor") {
        w        <- ci$w
        pair.var <- ci$var
        inferred <- inferCenteringType(w, tol)
        
        lab.aligned <- as.character(pm.aligned[[pair.var]])
        if (is.null(lab.aligned))
            stop("pair.meta[['", pair.var, "']] not found.")
        
        is.pos <- lab.aligned %in% names(w)[w > tol]
        if (!any(is.pos))
            stop("No rows match positive-weight levels in pair.meta[['", pair.var, "']].")
        
        neg.levels <- names(w)[w < -tol]
        denom <- sum(w[w > tol]); if (denom <= 0) stop("Sum of positive weights must be > 0.")
        
        mu.neg <- lapply(neg.levels, function(L) {
            idx <- (lab.aligned == L)
            if (!any(idx)) return(rep(NA_real_, ncol(yhat.all)))
            colMeans(yhat.all[idx, , drop = FALSE], na.rm = TRUE)
        })
        names(mu.neg) <- neg.levels
        
        neg.sum <- Reduce(`+`, Map(function(L) { (-w[L]) * mu.neg[[L]] }, neg.levels),
                          init = rep(0, ncol(yhat.all)))
        baseline <- neg.sum / denom
        
        base.mat <- matrix(rep(baseline, each = nrow(yhat.all)),
                           nrow = nrow(yhat.all), byrow = FALSE,
                           dimnames = list(rownames(yhat.all), colnames(yhat.all)))
        
        delta.df <- yhat.all[is.pos, , drop = FALSE] - base.mat[is.pos, , drop = FALSE]
        
        # block-wise summary
        delta.block <- NULL
        if (!is.null(block.vars)) {
            blk.cols <- intersect(block.vars, colnames(pm.aligned))
            if (length(blk.cols)) {
                block.aligned <- do.call(paste, c(pm.aligned[, blk.cols, drop = FALSE], sep = " | "))
                ublk <- unique(block.aligned)
                delta.block <- do.call(rbind, lapply(ublk, function(b) {
                    inb <- (block.aligned == b)
                    inb.pos <- which(inb & is.pos); if (!length(inb.pos)) return(NULL)
                    
                    mu.neg.b <- lapply(neg.levels, function(L) {
                        idx <- (lab.aligned == L) & inb
                        if (!any(idx)) return(rep(NA_real_, ncol(yhat.all)))
                        colMeans(yhat.all[idx, , drop = FALSE], na.rm = TRUE)
                    })
                    names(mu.neg.b) <- neg.levels
                    
                    neg.sum.b  <- Reduce(`+`, Map(function(L) { (-w[L]) * mu.neg.b[[L]] }, neg.levels),
                                         init = rep(0, ncol(yhat.all)))
                    baseline.b <- neg.sum.b / denom
                    mean.pos.b <- colMeans(yhat.all[inb.pos, , drop = FALSE], na.rm = TRUE)
                    shift.b    <- mean.pos.b - baseline.b
                    
                    data.frame(block   = b,
                               celltype = colnames(yhat.all),
                               shifts   = as.numeric(shift.b),
                               stringsAsFactors = FALSE)
                }))
            }
        }
        return(list(shifts = delta.df,
                    delta.block = delta.block,
                    inferred = inferred))
    }
    
    ## ----- CONTINUOUS CONTRAST PATH -----
    var <- ci$var
    if (!var %in% names(pm.aligned))
        stop("Continuous contrast variable '", var, "' not found in pair.meta.")
    x <- pm.aligned[[var]]
    if (!is.numeric(x))
        stop("pair.meta[['", var, "']] must be numeric for a continuous contrast.")
    
    if (is.null(coef.mat) || !(var %in% rownames(coef.mat)))
        stop("Provide coef.mat with a row named '", var, "' (rows = term names; cols = cell types).")
    
    # choose numeric baseline x0 (scalar) for continuous contrast
    x0.scalar <- NA_real_
    
    if (!is.null(x0.override)) {
        # If user supplies an anchor (from numeric_ref_used), use it directly
        x0.scalar <- as.numeric(x0.override)[1]
    } else {
        # Heuristics for pair_<var>_(mean|diff)
        m  <- regexec("^pair_([A-Za-z0-9.]+)_(mean|diff)$", var)
        mt <- regmatches(var, m)[[1]]
        if (length(mt) == 3L) {
            kind <- mt[3]
            if (kind == "diff") {
                # zero difference is natural baseline
                x0.scalar <- 0
            } else if (kind == "mean") {
                # fallback: mean of x when no explicit anchor
                x0.scalar <- mean(x, na.rm = TRUE)
            }
        }
    }
    
    # If still NA, use factor-based centering rule (as before)
    if (!is.finite(x0.scalar)) {
        if (!is.null(ci$center)) center.contrast <- ci$center
        if (is.null(center.contrast))
            stop("Provide centering via attr(contrast,'center'), 'center.contrast', ",
                 "or x0.override for continuous contrasts.")
        
        cf <- getContrastInfo(center.contrast)
        if (cf$kind != "factor")
            stop("'center.contrast' must be factor-like with names '<pair_var>=<level>'.")
        pair.var <- cf$var
        if (!(pair.var %in% names(pm.aligned)))
            stop("pair.meta lacks the factor variable '", pair.var, "' for centering.")
        
        x0.scalar <- contrastCenterX0(x,
                                      pair.level = as.character(pm.aligned[[pair.var]]),
                                      w = cf$w, tol = tol)
    }
    
    beta <- coef.mat[var, , drop = TRUE]
    x.c  <- x - x0.scalar
    delta.df <- x.c %*% t(beta)
    rownames(delta.df) <- rownames(yhat.all)
    colnames(delta.df) <- colnames(yhat.all)
    
    delta.block <- NULL
    if (!is.null(block.vars)) {
        blk.cols <- intersect(block.vars, colnames(pm.aligned))
        if (length(blk.cols)) {
            block.aligned <- do.call(paste, c(pm.aligned[, blk.cols, drop = FALSE], sep = " | "))
            ublk <- unique(block.aligned)
            delta.block <- do.call(rbind, lapply(ublk, function(b) {
                idx <- which(block.aligned == b); if (!length(idx)) return(NULL)
                shift.b <- colMeans(delta.df[idx, , drop = FALSE], na.rm = TRUE)
                data.frame(block   = b,
                           celltype = colnames(delta.df),
                           shifts   = as.numeric(shift.b),
                           stringsAsFactors = FALSE)
            }))
        }
    }
    
    list(
        shifts      = delta.df,
        delta.block = delta.block,
        inferred    = "continuous",
        x.center    = x0.scalar   # << scalar baseline used
    )
}


#' Extract fitted values for block permutation models
#'
#' This helper reconstructs fitted values and partial fits for block-based
#' permutation models, working in the **full model space** `F`. It separates:
#'   - full fitted values under the complete model,
#'   - partial fitted values for the core design `X`,
#'   - partial fitted values plus residual noise.
#'
#' Steps performed internally:
#'   1. Extract design matrices:
#'        - Convert `design.model$F` and `design.model$X` to matrices.
#'   2. Build the coefficient matrix:
#'        - Reshape `res$coef` (a flat numeric vector) into a matrix `B.F`
#'          with:
#'            * rows = columns of `F`,
#'            * columns = cell types (matching `p.dist`).
#'   3. Compute fitted values under the full model:
#'        - `y.fitted.all = F %*% B.F`, giving fitted values for every pair
#'          and cell type under the full design.
#'   4. Compute partial fits for the core design:
#'        - Identify columns of `X` that exist in `B.F`.
#'        - Compute `partial.fit.all = X %*% beta_X`, where `beta_X` are the
#'          corresponding rows of `B.F`.
#'   5. Add residual noise:
#'        - Combine partial fits with the residuals from the full model:
#'            * `partial.all = partial.fit.all + res$residuals`.
#'   6. Drop pairs with all-NA responses:
#'        - Use `p.dist` to identify rows (pairs) where all cell-type
#'          distances are `NA`.
#'        - Remove those rows from:
#'            * `y.fitted.all`,
#'            * `partial.fit.all`,
#'            * `partial.all`.
#'   7. Return a list with:
#'        - `partial.fit` — core-only fit (`X * beta_X`),
#'        - `partial` — core fit plus noise (`X * beta_X + e`),
#'        - `fitted` — full-model fit (`F * beta_F`).
#' @param res Result object from the block permutation/LM fit, containing
#'   coefficients (`coef`) and residuals (`residuals`).
#' @param p.dist Pairwise sample distances, used to
#'   identify rows with all-NA responses.
#' @param design.model Design object (typically `pair.model` or similar)
#'   containing matrices `F` and `X`.
#'
#' @return A list with:
#'   \describe{
#'     \item{partial.fit}{Matrix of core-only fitted values (`X * beta_X`).}
#'     \item{partial}{Matrix of fitted values plus residual noise.}
#'     \item{fitted}{Matrix of full-model fitted values (`F * beta_F`).}
#'   }
#'
#' @keywords internal
extractFitsBlock <- function(res, p.dist, design.model) {
  F <- as.matrix(design.model$F)
  X <- as.matrix(design.model$X)
  na.rows <- apply(is.na(p.dist), 1, all)
  # Coefs are on F's columns
  B.F <- matrix(res$coef, nrow = ncol(F), dimnames = list(colnames(F), colnames(p.dist)))

  # Full fitted values: yhat = F %*% B.F
  y.fitted.all <- as.matrix(F %*% B.F)

  # Partial *without noise*: X %*% beta_X
  xnames <- intersect(colnames(X), rownames(B.F))
  partial.fit.all <- as.matrix(X[, xnames, drop = FALSE] %*% B.F[xnames, , drop = FALSE])

  # Partial *with noise*: (X %*% beta_X) + residuals from F-fit
  partial.all <- partial.fit.all + as.matrix(res$residuals)
  
  ## Drop rows that had NA in the original response
  y.fitted.all    <- y.fitted.all[which(!na.rows), , drop = FALSE]
  partial.fit.all <- partial.fit.all[which(!na.rows), , drop = FALSE]
  partial.all     <- partial.all[which(!na.rows), , drop = FALSE]

  list(partial.fit = partial.fit.all,  # X * beta_X
       partial     = partial.all,      # X * beta_X + e
       fitted      = y.fitted.all)     # F * beta
}

#' Extract partial fitted values for Freedman–Lane permutation models
#'
#' This helper reconstructs partial fitted values for the core design `X`
#' under a Freedman–Lane permutation scheme. It places residualized responses
#' back into the full pair index space, filling non-core rows with `NA` and
#' dropping pairs with all-NA responses.
#'
#' Steps performed internally:
#'   1. Extract core design and dimensions:
#'        - Convert `design.model$X` to a matrix.
#'        - Record row names of `X` (pairs) and column names of `p.dist`
#'          (cell types).
#'   2. Initialize an all-NA matrix:
#'        - Allocate `y.r` as an `nrow(X) × ncol(p.dist)` matrix filled
#'          with `NA`, with row/column names from `X` and `p.dist`.
#'   3. Insert residualized values on core rows:
#'        - Determine core rows:
#'            * if `design.model$core.rows` is `NULL`, use all rows;
#'            * otherwise, use `which(design.model$core.rows)`.
#'        - Check that `res$y.resid` has the same number of rows as the
#'          selected core indices and the same number of columns as `p.dist`.
#'        - Assign `y.r[idx, ] <- res$y.resid`, leaving non-core rows as `NA`.
#'   4. Drop pairs with all-NA responses:
#'        - Use `p.dist` to identify rows where all cell-type distances are
#'          `NA`.
#'        - Remove those rows from `y.r`.
#'   5. Return the partial fitted matrix:
#'        - The returned matrix has:
#'            * rows = effective pairs used in the model,
#'            * columns = cell types,
#'            * `NA` in positions that were never modeled (non-core pairs).
#' @param res Result object from a Freedman–Lane permutation fit, expected to
#'   contain a matrix `y.resid` of residualized responses for core rows.
#' @param p.dist Sample pair distance matrix used to
#'   determine which pairs have all-NA responses.
#' @param design.model Design object (typically `pair.model` or similar)
#'   containing `X` and `core.rows`.
#'
#' @return A numeric matrix of partial fitted values (`X * beta_X`) aligned to
#'   the core rows and filtered to remove all-NA pairs.
#'
#' @keywords internal
extractFitsFL <- function(res, p.dist, design.model) {
    X    <- as.matrix(design.model$X)
    core <- design.model$core.rows  # logical length n, or NULL
    rn   <- rownames(X); cn <- colnames(p.dist)
    na.rows <- apply(is.na(p.dist), 1, all)
    y.r     <- matrix(NA_real_, nrow = nrow(X), ncol = ncol(p.dist),
                              dimnames = list(rn, cn))
    if (!is.null(res$y.resid)) {
        idx <- if (is.null(core)) seq_len(nrow(X)) else which(core)
        stopifnot(nrow(res$y.resid) == length(idx),
                  ncol(res$y.resid) == ncol(p.dist))
        y.r[idx, ] <- as.matrix(res$y.resid)           # X_core %*% beta_X
    } else { stop("Residualized values not provided.")}
    y.r <- y.r[which(!na.rows), , drop = FALSE]
    return(y.r)   # X * beta_X (on core rows if partial_core provided; NA elsewhere)
}


## Helpers for visualization

# infer centering & relevant levels from weights
# Return one of: "shift", "total", "var", "custom"
#' @keywords internal
inferCenteringType <- function(w, tol = 1e-8) {
  stopifnot(!is.null(names(w)))
  pos <- names(w)[w >  tol]
  neg <- names(w)[w < -tol]
  nz  <- names(w)[abs(w) > tol]

  is.same <- function(lab) grepl("^(.+)\\1$", lab)   # "AA" pattern (e.g., Group1Group1)
  all.same <- function(labs) length(labs) > 0 && all(vapply(labs, is.same, logical(1)))
  any.cross <- function(labs) any(!vapply(labs, is.same, logical(1)))

  # VAR: contrast between two same levels (AA vs BB), no cross terms involved
  if (length(nz) == 2 && sign(w[nz[1]]) != sign(w[nz[2]]) && all.same(nz)) {
    return("var")
  }

  # TOTAL: exactly one positive (must be cross) and one negative (must be same)
  if (length(pos) == 1 && length(neg) == 1 &&
      !is.same(pos) && is.same(neg)) {
    return("total")
  }

  # SHIFT: one positive (cross) and two negatives (both same)
  if (length(pos) == 1 && length(neg) == 2 &&
      !is.same(pos) && all.same(neg)) {
    return("shift")
  }
  "custom"
}

# names can be either:
#   - "<pair_var>=<level>" (factor-style contrast over levels)
#   - "<var>_pair<level>"  (pairwise design coefficient-space factor)
#   - "<numeric_var>"      (continuous; exactly one non-zero entry)
#' @keywords internal
getContrastInfo <- function(contrast.vec) {
  stopifnot(length(contrast.vec) > 0, !is.null(names(contrast.vec)))
  nm <- names(contrast.vec)

  # FACTOR CASE 1: "<var>=<level>" 
  has.eq <- grepl("=", nm, fixed = TRUE)
  if (any(has.eq)) {
    # Use only the entries that look like var=level
    nm.eq <- nm[has.eq]
    var   <- sub("=.+$", "", nm.eq[1])           # variable name before '='
    lev   <- sub("^.+?=", "", nm.eq)             # levels after '='
    w     <- setNames(as.numeric(contrast.vec[has.eq]), lev)
    return(list(kind = "factor", var = var, w = w, center = NULL))
  }

  # from here on: no '=' in names, so either continuous or coefficient-space factor
  nz_mask  <- abs(contrast.vec) > 0
  nz_names <- nm[nz_mask]

  # CONTINUOUS CASE: exactly one non-zero term 
  if (length(nz_names) == 1L) {
    ctr.center <- attr(contrast.vec, "center")  # for continuous contrasts
    return(list(
      kind   = "continuous",
      var    = nz_names,
      w      = setNames(as.numeric(contrast.vec[nz_mask]), nz_names),
      center = ctr.center
    ))
  }

  # FACTOR CASE 2: coefficient-space pair contrast "<var>_pair<level>" 
  # Here we expect multiple non-zero coefficients with names like "Group_pairGroup1_and_Group1".
  # We interpret them as a factor contrast over levels of <var>_pair.
  if (length(nz_names) > 1L) {
    pattern <- "^(.+?_pair)(.+)$"
    m       <- regexec(pattern, nz_names)
    parts   <- regmatches(nz_names, m)

    if (all(lengths(parts) == 3L)) {
      var.prefix <- parts[[1]][2L]                             # e.g. "Group_pair"
      lev        <- vapply(parts, function(p) p[3L], character(1L))  # e.g. "Group1_and_Group1"
      w          <- setNames(as.numeric(contrast.vec[nz_mask]), lev)
      return(list(kind = "factor", var = var.prefix, w = w, center = NULL))
    }
  }

  stop(
    "Cannot interpret contrast vector: either multiple non-zero coefficients ",
    "that do not match '<var>_pair<level>' or more than one non-zero term ",
    "without '=' in names.\n",
    "If this is a factor contrast, use names like 'var=level' or a '<var>_pair<level>' pattern.\n",
    "If this is continuous, ensure only one term has a non-zero weight."
  )
}


# x0 from factor-contrast weights applied to the predictor x (mirrors total/shift)
#' @keywords internal
contrastCenterX0 <- function(x, pair.level, w, tol = 1e-8) {
  pos.lv <- names(w)[w >  tol]
  neg.lv <- names(w)[w < -tol]
  if (!length(pos.lv)) stop("Factor centering contrast has no positive weights.")
  denom <- sum(w[pos.lv]); if (denom <= 0) stop("Sum of positive weights must be > 0.")

  mu.x.neg <- lapply(neg.lv, function(L) {
    idx <- (pair.level == L)
    if (!any(idx)) return(NA_real_)
    mean(x[idx], na.rm = TRUE)
  })
  names(mu.x.neg) <- neg.lv

  num <- sum(mapply(function(L, mu) { (-w[L]) * mu }, neg.lv, mu.x.neg))
  num / denom
}


# helper: detect factor vs numeric for a single column name in a data.frame
#' @keywords internal
isContinuousCol <- function(df, col) {
  isTRUE(col %in% names(df)) && is.numeric(df[[col]])
}
