# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @param sample_per_cell must contains ids from 0 to n_samples-1
#' @param n_samples must be equal to maximum(sample_per_cell) + 1
NULL

clusterFreeZScoreMat <- function(count_mat, sample_per_cell, nn_ids, is_ref, min_n_samp_per_cond = 2L, min_n_obs_per_samp = 1L, robust = TRUE, norm_both = FALSE, min_z = 0.01, verbose = TRUE, n_cores = 1L) {
    .Call('_cacoa_clusterFreeZScoreMat', PACKAGE = 'cacoa', count_mat, sample_per_cell, nn_ids, is_ref, min_n_samp_per_cond, min_n_obs_per_samp, robust, norm_both, min_z, verbose, n_cores)
}

estimateClusterFreeExpressionShiftsC <- function(cm, sample_per_cell, nn_ids, is_ref, min_n_between = 1L, min_n_within = 1L, min_n_obs_per_samp = 1L, norm_all = FALSE, verbose = TRUE, n_cores = 1L, dist = "cosine", log_vecs = FALSE) {
    .Call('_cacoa_estimateClusterFreeExpressionShiftsC', PACKAGE = 'cacoa', cm, sample_per_cell, nn_ids, is_ref, min_n_between, min_n_within, min_n_obs_per_samp, norm_all, verbose, n_cores, dist, log_vecs)
}

mapIds <- function(ids_vec, id_map) {
    .Call('_cacoa_mapIds', PACKAGE = 'cacoa', ids_vec, id_map)
}

projdiff <- function(mat, g1, g2) {
    .Call('_cacoa_projdiff', PACKAGE = 'cacoa', mat, g1, g2)
}

