# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @param adj_mat adjacency matrix with 1 on the position (r,c) if the cell r is adjacent to the cell c
NULL

#' @param sample_per_cell must contains ids from 0 to n_samples-1
#' @param n_samples must be equal to maximum(sample_per_cell) + 1
NULL

clusterFreeZScoreMat <- function(adj_mat, count_mat, is_control, min_z = 0.01, normalize_both = FALSE, verbose = TRUE, n_cores = 1L) {
    .Call('_cacoa_clusterFreeZScoreMat', PACKAGE = 'cacoa', adj_mat, count_mat, is_control, min_z, normalize_both, verbose, n_cores)
}

estimateClusterFreeExpressionShiftsC <- function(cm, sample_per_cell, nn_ids, is_ref, min_n_between = 1L, min_n_within = 1L, min_n_obs_per_samp = 1L, norm_all = FALSE, robust = TRUE, verbose = TRUE, n_cores = 1L) {
    .Call('_cacoa_estimateClusterFreeExpressionShiftsC', PACKAGE = 'cacoa', cm, sample_per_cell, nn_ids, is_ref, min_n_between, min_n_within, min_n_obs_per_samp, norm_all, robust, verbose, n_cores)
}

projdiff <- function(mat, g1, g2) {
    .Call('_cacoa_projdiff', PACKAGE = 'cacoa', mat, g1, g2)
}

