# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @param adj_mat adjacency matrix with 1 on the position (r,c) if the cell r is adjacent to the cell c
NULL

clusterFreeZScoreMat <- function(adj_mat, count_mat, is_control, verbose = TRUE, min_z = 0.01) {
    .Call('_cacoa_clusterFreeZScoreMat', PACKAGE = 'cacoa', adj_mat, count_mat, is_control, verbose, min_z)
}

estimateClusterFreeExpressionShifts <- function(rmat, rfactor, nn_ids, is_ref, verbose = TRUE) {
    .Call('_cacoa_estimateClusterFreeExpressionShifts', PACKAGE = 'cacoa', rmat, rfactor, nn_ids, is_ref, verbose)
}

projdiff <- function(mat, g1, g2) {
    .Call('_cacoa_projdiff', PACKAGE = 'cacoa', mat, g1, g2)
}

